---

- name: Create s3-minio folder
  ansible.builtin.file:
    path: "{{ role_regards_s3_minio_workspace_local }}s3-minio"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_s3_minio_container_run_user }}"
    group: "{{ role_regards_s3_minio_container_run_group }}"
    setype: "{{ role_regards_s3_minio_setype }}"
    seuser: "{{ role_regards_s3_minio_seuser }}"
  when: role_regards_s3_minio_is_defined|bool
