#
# Copyright 2018-2020, CS GROUP – France, http://www.c-s.fr
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
- name: "[DEBIAN] Update basic packages"
  apt:
    name:
      - ntp
      - tcpdump
      - wget
      - openssl
      - curl
    state: latest
    update_cache: yes

- name: "[DEBIAN] Install Pip3"
  apt:
    name:
      - python3-pip
    state: latest
    update_cache: yes
  when: python_version == 3

- name: "[DEBIAN] Install Pip2"
  apt:
    name:
      - python2-pip
    state: latest
    update_cache: yes
  when: python_version == 2
