---
- name: Create REGARDS structure
  ansible.builtin.file:
    path: "{{ role_regards_elasticsearch_workspace_local_path }}"
    state: directory
    mode: '0750'
    owner: "{{ role_regards_elasticsearch_workspace_local_container_root_user }}"
    group: "{{ role_regards_elasticsearch_workspace_local_container_root_group }}"
    setype: "{{ role_regards_elasticsearch_workspace_local_setype }}"
    seuser: "{{ role_regards_elasticsearch_workspace_local_seuser }}"
  when: role_regards_elasticsearch_workspace_local_elasticsearch_defined

- name: Create ES tmpjna folder
  ansible.builtin.file:
    path: "{{ role_regards_elasticsearch_workspace_local_path }}tmpjna"
    state: directory
    mode: '2770'
    owner: "{{ role_regards_elasticsearch_workspace_local_container_run_user }}"
    group: "{{ role_regards_elasticsearch_workspace_local_container_run_group }}"
    setype: "{{ role_regards_elasticsearch_workspace_local_setype }}"
    seuser: "{{ role_regards_elasticsearch_workspace_local_seuser }}"
  when: role_regards_elasticsearch_workspace_local_elasticsearch_defined

- name: Create ES data folder
  ansible.builtin.file:
    path: "{{ role_regards_elasticsearch_workspace_local_path }}data"
    state: directory
    mode: '2770'
    owner: "{{ role_regards_elasticsearch_workspace_local_container_run_user }}"
    group: "{{ role_regards_elasticsearch_workspace_local_container_run_group }}"
    setype: "{{ role_regards_elasticsearch_workspace_local_setype }}"
    seuser: "{{ role_regards_elasticsearch_workspace_local_seuser }}"
  when: role_regards_elasticsearch_workspace_local_elasticsearch_defined and role_regards_elasticsearch_workspace_local_elasticsearch_data_active

- name: Create ES backup folder
  ansible.builtin.file:
    path: "{{ role_regards_elasticsearch_workspace_local_path }}backup"
    state: directory
    mode: '2770'
    owner: "{{ role_regards_elasticsearch_workspace_local_container_run_user }}"
    group: "{{ role_regards_elasticsearch_workspace_local_container_run_group }}"
    setype: "{{ role_regards_elasticsearch_workspace_local_setype }}"
    seuser: "{{ role_regards_elasticsearch_workspace_local_seuser }}"
  when: role_regards_elasticsearch_workspace_local_elasticsearch_defined and role_regards_elasticsearch_workspace_local_elasticsearch_backup_active
