---
  - name: Generate stacks files
    template:
      src: "{{ item }}"
      dest: "{{ role_regards_stack_stack }}"
      mode: '0740'
      owner: "{{ role_regards_stack_container_root_user }}"
      group: "{{ role_regards_stack_container_root_group }}"
    with_items:
      - regards-stack.yml
      - elastic.yml
      - logs.yml
      - doc.yml
      - mail.yml
      - postgresql.yml
      - rabbitmq.yml
      - workers.yml
    become: true

  - set_fact:
      launch_swarm: >
        docker stack deploy 
        -c {{ role_regards_stack_stack }}regards-stack.yml 
        -c {{ role_regards_stack_stack }}elastic.yml 
        {% if role_regards_stack_cots.elasticsearch_logs is defined or role_regards_stack_cots.kibana_logs is defined or role_regards_stack_cots.fluent is defined %}
        -c {{ role_regards_stack_stack }}logs.yml 
        {% endif %}
        {% if role_regards_stack_cots.doc is defined %}
        -c {{ role_regards_stack_stack }}doc.yml 
        {% endif %}
        {% if role_regards_stack_cots.maildev is defined %}
        -c {{ role_regards_stack_stack }}mail.yml 
        {% endif %}
        {% if role_regards_stack_cots.postgres is defined or role_regards_stack_cots.phppgadmin is defined %}
        -c {{ role_regards_stack_stack }}postgresql.yml
        {% endif %}
        -c {{ role_regards_stack_stack }}rabbitmq.yml 
        {% if role_regards_stack_workers | length > 0 %}
        -c {{ role_regards_stack_stack }}workers.yml 
        {% endif %}
        --with-registry-auth 
        {{ role_regards_stack_stack_name }}

  - name: Run REGARDS
    command: "{{ launch_swarm }}"
