---
- name: Generate mandatory stacks files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ role_regards_stack_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_container_root_user }}"
    group: "{{ role_regards_stack_container_root_group }}"
  with_items:
    - regards-stack.yml
    - global-mounts.yml
    - rabbitmq.yml

- name: Generate elastic stack file using external role
  ansible.builtin.include_role:
    name: regards-stack-elasticsearch

- name: Generate haproxy stack file using external role
  ansible.builtin.include_role:
    name: regards-stack-haproxy

- name: Generate network stack file using external role
  ansible.builtin.include_role:
    name: regards-stack-network

- name: Generate logs stack file using external role
  ansible.builtin.include_role:
    name: regards-stack-logs

- name: Generate doc.yml
  ansible.builtin.template:
    src: doc.yml
    dest: "{{ role_regards_stack_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_container_root_user }}"
    group: "{{ role_regards_stack_container_root_group }}"
  when: role_regards_stack_cots.doc is defined

- name: Generate Minio stack file using external role
  ansible.builtin.include_role:
    name: regards-stack-minio

- name: Generate mail.yml
  ansible.builtin.template:
    src: mail.yml
    dest: "{{ role_regards_stack_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_container_root_user }}"
    group: "{{ role_regards_stack_container_root_group }}"
  when: role_regards_stack_cots.maildev is defined

- name: Generate postgresql.yml
  ansible.builtin.template:
    src: postgresql.yml
    dest: "{{ role_regards_stack_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_container_root_user }}"
    group: "{{ role_regards_stack_container_root_group }}"
  when: role_regards_stack_cots.postgres is defined or role_regards_stack_cots.phppgadmin is defined

- name: Generate workers.yml
  ansible.builtin.template:
    src: workers.yml
    dest: "{{ role_regards_stack_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_container_root_user }}"
    group: "{{ role_regards_stack_container_root_group }}"
  when: role_regards_stack_workers | length > 0
