---

role_regards_fluentd_workspace_local_logs: "{{ group_workdir_local }}{{group_stack_name}}/workspace/regards/logs/"
role_regards_fluentd_conf_local: "{{ group_workdir_local }}{{ group_stack_name }}/config/fluentd/"


  
role_regards_fluentd_container_root_user: "{{ group_container_root_user }}"
role_regards_fluentd_container_root_group: "{{ group_container_root_group }}"
role_regards_fluentd_container_run_user: "{{ group_container_run_user }}"
role_regards_fluentd_container_run_group: "{{ group_container_run_group }}"
role_regards_fluentd_setype: "{{ group_setype }}"
role_regards_fluentd_seuser: "{{ group_seuser }}"

role_regards_fluentd_logs_directory:
  - config
  - registry
  - gateway
  - admin-instance
  - admin
  - authentication
  - dam
  - notifier
  - fem
  - catalog
  - access-instance
  - access-project
  - front
  - storage
  - order
  - ingest
  - dataprovider
  - processing
  - worker-manager

role_regards_fluentd_workers: "{{ group_docker_workers | default([]) }}"

role_regards_fluentd_new_logging_regex: "{{ group_config_mservices.get('legacy_spring', false) }}"
