---
  - name: Delete local node directory (retry when containers are stopping too slowly)
    ansible.builtin.command: "rm -rf {{ role_regards_erase_node_rootdir_local }}"
    retries: 3 
    delay: 5
    register: result
    until: result is not failed
    become: true
