---
- name: Create rabbitMQ certificates folder
  ansible.builtin.file:
    dest: "{{ role_regards_rabbitmq_config_folder_certificates }}"
    state: directory
    mode: '0770'
    owner: "{{ role_regards_rabbitmq_config_container_root_user }}"
    group: "{{ role_regards_rabbitmq_config_container_root_group }}"
    setype: "{{ role_regards_rabbitmq_config_setype }}"
    seuser: "{{ role_regards_rabbitmq_config_seuser }}"

- name: Copy RabbitMQ certificates
  ansible.builtin.copy:
    src: "{{ role_regards_rabbitmq_config_ssl_location_inside_playbook }}{{ item }}"
    dest: "{{ role_regards_rabbitmq_config_folder_certificates }}{{ item }}"
    mode: '0440'
    owner: "{{ role_regards_rabbitmq_config_container_root_user }}"
    group: "{{ role_regards_rabbitmq_config_container_root_group }}"
    setype: "{{ role_regards_rabbitmq_config_setype }}"
    seuser: "{{ role_regards_rabbitmq_config_seuser }}"
  with_items: 
    - "{{ role_regards_rabbitmq_config_ssl_certificates_conf.ca }}"
    - "{{ role_regards_rabbitmq_config_ssl_certificates_conf.crt }}"
    - "{{ role_regards_rabbitmq_config_ssl_certificates_conf.key }}"
