---
- ansible.builtin.include_tasks: config.yml
  when: role_regards_rabbitmq_config_is_defined|bool

- ansible.builtin.include_tasks: certificates.yml
  when: role_regards_rabbitmq_config_ssl_active|bool
