---

- name: Add files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0750'
    owner: "{{ role_regards_elasticsearch_sidecar_container_root_user }}"
    group: "{{ role_regards_elasticsearch_sidecar_container_root_group }}"
  with_items:
    - send-kibana-dashboard.sh
    - kibana-settings.json
    - logs_kibana_visu.json
  become: true

- name: Run container to init Kibana Logs dashboard
  docker_container:
    name: "postinstall-kibana-logs"
    image: "{{ role_regards_elasticsearch_sidecar_registry }}/regards-bash"
    pull: true
    ansible.builtin.command: bash /send-kibana-dashboard.sh
    detach: false
    network_mode: "{{ role_regards_elasticsearch_sidecar_docker_network_name }}"
    networks_cli_compatible: true
    read_only: true
    cleanup: true
    networks:
      - name: "{{ role_regards_elasticsearch_sidecar_docker_network_name }}"
    volumes:
      - /tmp/send-kibana-dashboard.sh:/send-kibana-dashboard.sh
      - /tmp/kibana-settings.json:/kibana-settings.json
      - /tmp/logs_kibana_visu.json:/logs_kibana_visu.json
  vars:
    ansible_python_interpreter: "env python{{ python_version }}"

- name: Delete files
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - send-kibana-dashboard.sh
    - kibana-settings.json
    - logs_kibana_visu.json
  become: true
