---
- name: Add tmp files to /tmp/
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0750'
    owner: "{{ role_regards_kibana_logs_postinstall_container_root_user }}"
    group: "{{ role_regards_kibana_logs_postinstall_container_root_group }}"
  with_items:
    - start.sh
    - kibana-settings.ndjson
    - logs_kibana_visu.ndjson
    - space.ndjson
  become: true
  when: role_regards_kibana_logs_postinstall_kibana_active|bool

- name: Run container to init Kibana Logs dashboard
  docker_container:
    name: "postinstall-kibana-logs"
    validate_certs: "{{ role_regards_kibana_logs_postinstall_validate_certs }}"
    image: "{{ role_regards_kibana_logs_postinstall_registry }}/regards-bash:{{ role_regards_kibana_logs_postinstall_image_version }}"
    pull: true
    command: bash /start.sh
    detach: false
    network_mode: none
    networks_cli_compatible: true
    read_only: true
    cleanup: true
    # container_default_behavior: no_defaults
    log_driver: json-file
    networks:
      - name: "{{ role_regards_kibana_logs_postinstall_docker_network_name }}"
    volumes:
      - /tmp/start.sh:/start.sh
      - /tmp/kibana-settings.ndjson:/kibana-settings.ndjson
      - /tmp/space.ndjson:/space.ndjson
      - /tmp/logs_kibana_visu.ndjson:/logs_kibana_visu.ndjson
  vars:
    ansible_python_interpreter: "env python{{ python_version }}"
  when: role_regards_kibana_logs_postinstall_kibana_active|bool

- name: Delete tmp files
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - start.sh
    - kibana-settings.ndjson
    - logs_kibana_visu.ndjson
    - space.ndjson
  become: true
  when: role_regards_kibana_logs_postinstall_kibana_active|bool
