---
- name: Init Postgres nb connections
  ansible.builtin.set_fact:
    postgres_nb_connections: 0

- name: Iterate over microservice
  ansible.builtin.include_tasks: computeNbConnection.yml
  loop: "{{ role_regards_postgres_config_mservices | dict2items }}"
  loop_control:
    loop_var: mservice

- name: Copy configuraton
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ role_regards_postgres_config_conf_local }}"
    mode: '0555'
    owner: "{{ role_regards_postgres_config_container_root_user }}"
    group: "{{ role_regards_postgres_config_container_root_group }}"
  with_items:
    - init.sql
    - postgresql.conf
