---
  - name: Refresh the REGARDS with all the conf within the Ansible project
    hosts: regards_nodes
    become: true
  
    roles:
      - regards-logback
      - regards-fluentd
      - regards-mconfig
      - regards-front


  - name: Launch stack
    hosts: master

    roles:
      - regards-stack
