---
- name: Run postinstall scripts to update CoTS configuration
  hosts: regards_nodes:!swarm_manager_only_nodes
  roles:
    - regards-elasticsearch-postinstall
    # - regards-kibana-logs-postinstall
