---
- name: Install REGARDS on master node
  hosts: master
  roles:
    - regards-init-master

- name: Install REGARDS plugins on all nodes
  hosts: regards_nodes:!swarm_manager_only_nodes
  roles:
    - regards-plugins-workspace-local

- name: Install REGARDS local workspaces on every nodes
  hosts: regards_nodes:!swarm_manager_only_nodes
  become: true
  roles:
    - regards-microservices-workspace-local
    - regards-logs-workspace-local
    - regards-postgres-workspace-local
    - regards-s3-minio-workspace-local
    - regards-elasticsearch-workspace-local
    - regards-rabbitmq-workspace-local
    - regards-workers

- name: Initiate NFS workspaces 
  hosts: slaves[0]
  roles:
    - regards-init-nfs-workspaces
    - regards-plugins-workspace-nfs

- name: Install SWARM configs and secrets files on master node
  hosts: master
  become: true
  roles:
    - regards-front
    - regards-front-ssl
    - regards-front-footer
    - regards-fluentd-config
    - regards-postgres-config
    - regards-elasticsearch-config
    - regards-haproxy-config
    - regards-rabbitmq-config
    - regards-mconfig
    - regards-logback
    - regards-mounts-secrets-configs
    - regards-ca-certificates

- name: Launch stack
  hosts: master
  roles:
    - regards-stack
