---
- name: Refresh SWARM configs and secrets files on master node
  hosts: master
  become: true
  roles:
    - regards-front-footer
    - regards-mconfig
    - regards-mounts-secrets-configs

- name: Launch stack
  hosts: master
  roles:
    - regards-stack
