version: '3.7'
services:

{% if role_regards_stack_cots.elasticsearch is defined %}
  rs-elasticsearch:
    image: {{role_regards_stack_registry}}/regards-elasticsearch:{{ role_regards_stack_cots.elasticsearch.tag | default("latest") }}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    hostname: rs-elasticsearch
    read_only: true
    networks:
      - {{role_regards_stack_docker_network_name}}
    volumes:
{% if role_regards_stack_cots_configuration_use_ungranular_workspace_on_workdir_network %}
      - {{ role_regards_stack_workdir_network }}:/share
{% else %}
      - {{role_regards_stack_workspace_local}}elasticsearch/data:/usr/share/elasticsearch/data
      - {{role_regards_stack_workspace_local}}elasticsearch/backup:/usr/share/elasticsearch/backup
{% endif %}
      - {{role_regards_stack_workspace_local}}elasticsearch/tmpjna:/tmpjna
      - {{role_regards_stack_config}}elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /usr/share/elasticsearch/logs
{% if role_regards_stack_cots.elasticsearch.http is defined or role_regards_stack_cots.elasticsearch.client is defined %}
    ports:
{% if role_regards_stack_cots.elasticsearch.http is defined %}
      - "{{ role_regards_stack_cots.elasticsearch.http }}:9200"
{% endif %}
{% if role_regards_stack_cots.elasticsearch.client is defined %}
      - "{{ role_regards_stack_cots.elasticsearch.client }}:9300"
{% endif %}
{% endif %}
    environment:
      - cluster.name={{ role_regards_stack_cots_configuration.elasticsearch.cluster_name }}
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2000m -Xmx2000m -Djna.tmpdir=/tmpjna"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
{% if role_regards_stack_attach_cots_to_specific_node|bool %}
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == {{ hostvars[groups.elasticsearch[0]].ansible_host }}]
{% endif %}
{% endif %}

{% if role_regards_stack_cots.kibana is defined %}
  rs-kibana:
    image: {{role_regards_stack_registry}}/regards-kibana:{{ role_regards_stack_cots.kibana.tag | default("latest") }}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    hostname: rs-kibana
    read_only: true
    networks:
      - {{role_regards_stack_docker_network_name}}
    volumes:
      - type: tmpfs
        target: /usr/share/kibana/optimize/
{% if role_regards_stack_cots.kibana.http is defined %}
    ports:
      - "{{ role_regards_stack_cots.kibana.http }}:5601"
{% endif %}
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
{% endif %}
