version: '3.7'

# Config name must contains less than 32 [a-zA-Z0-9-_.] caracters
configs:
{% if role_regards_stack_cots.elasticsearch_logs is defined %}
  rs-elasticsearch-logs_elasticsearch.yml:
    name: elasticsearch_logs_config_file_${CHECKSUM_RS_ELASTICSEARCH_LOGS_ELASTICSEARCH_LOGS_YML}
    file: {{ role_regards_stack_config }}elasticsearch/elasticsearch-logs.yml
{% endif %}
{% if role_regards_stack_cots.fluent is defined %}
  rs-fluent_fluent.conf:
    name: fluent_config_file_${CHECKSUM_RS_FLUENT_FLUENT_CONF}
    file: {{ role_regards_stack_config }}fluentd/fluent.conf
{% endif %}

{% if role_regards_stack_cots.elasticsearch_logs is defined %}
volumes:
  data-es-logs-datavolume:
    driver: local
    driver_opts:
{% if role_regards_stack_volume_elasticsearch_logs_data.nfs is defined %}
{% for nfs_server in role_regards_stack_top_level_nfs_servers %}
{% if nfs_server.name == role_regards_stack_volume_elasticsearch_logs_data.nfs %}
      type: {{ nfs_server.config.get('type', 'nfs') }}
      o: "{{ nfs_server.config.o }}"
      device: "{{ nfs_server.config.device_prefix }}{{ role_regards_stack_volume_elasticsearch_logs_data.get('device_postfix', 'elasticsearch/data-logs') }}"
{% endif %}
{% endfor %}
{% else %}
      type: none
      o: bind
      device: {{ role_regards_stack_workspace_local }}elasticsearch/data-logs
{% endif %}

  backup-es-logs-datavolume:
    driver: local
    driver_opts:
{% if role_regards_stack_volume_elasticsearch_logs_backup.nfs is defined %}
{% for nfs_server in role_regards_stack_top_level_nfs_servers %}
{% if nfs_server.name == role_regards_stack_volume_elasticsearch_logs_backup.nfs %}
      type: {{ nfs_server.config.get('type', 'nfs') }}
      o: "{{ nfs_server.config.o }}"
      device: "{{ nfs_server.config.device_prefix }}{{ role_regards_stack_volume_elasticsearch_logs_backup.get('device_postfix', 'elasticsearch/backup-logs') }}"
{% endif %}
{% endfor %}
{% else %}
      type: none
      o: bind
      device: {{ role_regards_stack_workspace_local }}elasticsearch/backup-logs
{% endif %}

  tmpjna-es-logs-datavolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: {{ role_regards_stack_workspace_local }}elasticsearch/tmpjna-logs
{% endif %}

services:
{% if role_regards_stack_cots.elasticsearch_logs is defined %}
  rs-logs-elasticsearch:
    image: {{role_regards_stack_registry}}/regards-elasticsearch:{{ role_regards_stack_cots.elasticsearch_logs.tag | default("latest") }}
{%if (role_regards_stack_cots.elasticsearch_logs.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.elasticsearch_logs.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
{% if role_regards_stack_cots.rabbitmq.global_service is defined %}
    hostname: "rs-logs-elasticsearch-{{ '{{' }}.Node.Hostname{{ '}}' }}"
{% else %}
    hostname: rs-logs-elasticsearch
{% endif %}
    read_only: true
{% if role_regards_stack_cots.elasticsearch_logs.node_label_placement_constraint is defined or role_regards_stack_cots.elasticsearch_logs.global_service is defined %}
    deploy:
{% if role_regards_stack_cots.elasticsearch_logs.global_service is defined %}
      mode: global
      endpoint_mode: dnsrr
{% endif %}
{% if role_regards_stack_cots.elasticsearch_logs.node_label_placement_constraint is defined %}
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.elasticsearch_logs.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.elasticsearch_logs.node_label_placement_constraint.value }}
{% endif %}
{% endif %}
    networks:
      - {{ role_regards_stack_docker_network_name }}
    volumes:
      - type: volume
        source: data-es-logs-datavolume
        target: /usr/share/elasticsearch/data/esdata
      - type: volume
        source: backup-es-logs-datavolume
        target: /usr/share/elasticsearch/backup
      - type: volume
        source: tmpjna-es-logs-datavolume
        target: /tmpjna
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /usr/share/elasticsearch/logs
    configs:
      - source: rs-elasticsearch-logs_elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
{% if role_regards_stack_cots.elasticsearch_logs.http is defined or role_regards_stack_cots.elasticsearch_logs.client is defined %}
    ports:
{% if role_regards_stack_cots.elasticsearch_logs.http is defined %}
      - "{{ role_regards_stack_cots.elasticsearch_logs.http }}:9200"
{% endif %}
{% if role_regards_stack_cots.elasticsearch_logs.client is defined %}
      - "{{ role_regards_stack_cots.elasticsearch_logs.client }}:9300"
{% endif %}
{% endif %}
    environment:
      - "node.name=rs-logs-elasticsearch-{{ '{{' }}.Node.Hostname{{ '}}' }}"
      - cluster.name={{ role_regards_stack_cots_configuration.elasticsearch_logs.cluster_name }}
      - bootstrap.memory_lock=true
      - ES_PATH_DATA=/usr/share/elasticsearch/data/esdata
      - "ES_JAVA_OPTS=-Xms{{ role_regards_stack_cots.elasticsearch_logs.memoryLimit | default("500m") }} -Xmx{{ role_regards_stack_cots.elasticsearch_logs.memoryLimit | default("500m") }} -Djna.tmpdir=/tmpjna"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    logging:
{% if role_regards_stack_cots.elasticsearch_logs.logging is defined %}
      {{ role_regards_stack_cots.elasticsearch_logs.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}

{% if role_regards_stack_cots.fluent is defined %}
  rs-fluent:
    image: {{role_regards_stack_registry}}/regards-fluent:{{ role_regards_stack_cots.fluent.tag | default("latest") }}
{%if (role_regards_stack_cots.fluent.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.fluent.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    hostname: rs-fluent
    read_only: true
{% if not role_regards_stack_all_logs_inside_same_network_storage|bool or role_regards_stack_cots.fluent.node_label_placement_constraint is defined %}
    deploy:
{% if not role_regards_stack_all_logs_inside_same_network_storage|bool %}
      mode: global
{% endif %}
{% if role_regards_stack_cots.fluent.node_label_placement_constraint is defined %}
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.fluent.node_label_placement_constraint.key }} {{ role_regards_stack_cots.fluent.node_label_placement_constraint.equality_operator | default('==') }} {{ role_regards_stack_cots.fluent.node_label_placement_constraint.value }}
{% endif %}
{% endif %}
    networks:
      - {{ role_regards_stack_docker_network_name }}
    volumes:
{% for mservice in role_regards_stack_volume_mservices_logs %}
      - type: volume
        source: logs-{{ mservice }}-datavolume
        target: /logs/{{ mservice }}
{% endfor %}
{% for worker in role_regards_stack_workers %}
      - {{ role_regards_stack_workspace_local }}regards/workers/{{ worker.name }}/logs:/logs/{{ worker.name }}
{% endfor %}
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /fluentd/logs
    configs:
      - source: rs-fluent_fluent.conf
        target: /fluentd/etc/fluent.conf
    logging:
{% if role_regards_stack_cots.fluent.logging is defined %}
      {{ role_regards_stack_cots.fluent.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}



{% if role_regards_stack_cots.kibana_logs is defined %}
  rs-logs-kibana:
    image: {{role_regards_stack_registry}}/regards-kibana:{{ role_regards_stack_cots.kibana_logs.tag | default("latest") }}
{%if (role_regards_stack_cots.kibana_logs.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.kibana_logs.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    hostname: rs-logs-kibana
    read_only: true
{% if role_regards_stack_cots.kibana_logs.node_label_placement_constraint is defined %}
    deploy:
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.kibana_logs.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.kibana_logs.node_label_placement_constraint.value }}
{% endif %}
    networks:
      - {{ role_regards_stack_docker_network_name }}
    volumes:
      - type: tmpfs
        target: /usr/share/kibana/data/
    environment:
      - ELASTICSEARCH_HOSTS=http://rs-logs-elasticsearch:9200
{% if role_regards_stack_cots.kibana_logs.http is defined %}
    ports:
      - "{{ role_regards_stack_cots.kibana_logs.http }}:5601"
{% endif %}
    logging:
{% if role_regards_stack_cots.kibana_logs.logging is defined %}
      {{ role_regards_stack_cots.kibana_logs.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}
