version: '3.9'
services:

{% if role_regards_stack_cots.maildev is defined %}
  rs-maildev:
    image: {{role_regards_stack_registry}}/regards-maildev:{{ role_regards_stack_cots.maildev.tag | default("latest") }}
{%if (role_regards_stack_cots.maildev.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.maildev.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    networks:
      - {{role_regards_stack_docker_network_name}}
{% if role_regards_stack_cots.maildev.http is defined %}
    ports:
      - "{{ role_regards_stack_cots.maildev.http }}:1080"
{% endif %}
    deploy:
      restart_policy:
        condition: any
        delay: {{ role_regards_stack_restart_policy.delay }}
        max_attempts: {{ role_regards_stack_restart_policy.max_attempts }}
        window: {{ role_regards_stack_restart_policy.window }}
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
          pids: 100000
        reservations:
          cpus: '0.1'
          memory: 32M
{% if role_regards_stack_cots.maildev.node_label_placement_constraint is defined %}
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.maildev.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.maildev.node_label_placement_constraint.value }}
{% endif %}
{% endif %}
