version: '3.7'
services:

{% if role_regards_stack_cots.postgres is defined %}
  rs-postgres:
    image: {{ role_regards_stack_registry }}/regards-database:{{ role_regards_stack_cots.postgres.tag | default("latest") }}
{%if (role_regards_stack_cots.postgres.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.postgres.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{ role_regards_stack_container_run_uid }}:{{ role_regards_stack_container_run_gid }}"
    hostname: rs-postgres
    read_only: true
{% if role_regards_stack_cots.postgres.node_label_placement_constraint is defined %}
    deploy:
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.postgres.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.postgres.node_label_placement_constraint.value }}
{% endif %}
    networks:
      - {{ role_regards_stack_docker_network_name }}
    environment:
      - POSTGRES_PASSWORD={{ role_regards_stack_config_postgres.password }}
      - POSTGRES_USER={{ role_regards_stack_config_postgres.user }}
    volumes:
      - {{ role_regards_stack_workspace_local }}postgresql:/var/lib/postgresql/data
      - {{ role_regards_stack_config }}postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - {{ role_regards_stack_config }}postgres/postgresql.conf:/etc/postgresql.conf:ro
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run/postgresql
{% if role_regards_stack_cots.postgres.client is defined %}
    ports:
      - "{{ role_regards_stack_cots.postgres.client }}:5432"
{% endif %}
    logging:
{% if role_regards_stack_cots.postgres.logging is defined %}
      {{ role_regards_stack_cots.postgres.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}

{% if role_regards_stack_cots.phppgadmin is defined %}
  rs-phppgadmin:
    image: {{ role_regards_stack_registry }}/regards-phppgadmin:{{ role_regards_stack_cots.phppgadmin.tag | default("latest") }}
{%if (role_regards_stack_cots.phppgadmin.configuration | default({})).labels is defined %}
    labels:
{% for key, value in role_regards_stack_cots.phppgadmin.configuration.labels.items() %}
      {{ key }}: "{{value}}"
{% endfor %}
{% endif %}
    user: "{{ role_regards_stack_container_run_uid }}:{{ role_regards_stack_container_run_gid }}"
    hostname: rs-phppgadmin
    read_only: true
{% if role_regards_stack_cots.phppgadmin.node_label_placement_constraint is defined %}
    deploy:
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.phppgadmin.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.phppgadmin.node_label_placement_constraint.value }}
{% endif %}
    networks:
      - {{ role_regards_stack_docker_network_name }}
{% if role_regards_stack_cots.phppgadmin.db is defined or role_regards_stack_cots.phppgadmin.setting_owned_only is defined or role_regards_stack_cots.phppgadmin.setting_raw_rows is defined or role_regards_stack_cots.phppgadmin.setting_raw_chars is defined or role_regards_stack_cots.phppgadmin.setting_main_theme is defined or role_regards_stack_cots.phppgadmin.setting_sidebar_left_width is defined %}
    environment:
{% if role_regards_stack_cots.phppgadmin.db is defined %}
      - 'DB_CONFIG={{ role_regards_stack_cots.phppgadmin.db | to_json }}'
{% endif %}
{% if role_regards_stack_cots.phppgadmin.setting_owned_only is defined %}
      - OWNED_ONLY={{ role_regards_stack_cots.phppgadmin.setting_owned_only }}
{% endif %}
{% if role_regards_stack_cots.phppgadmin.setting_raw_rows is defined %}
      - MAX_ROWS={{ role_regards_stack_cots.phppgadmin.setting_raw_rows }}
{% endif %}
{% if role_regards_stack_cots.phppgadmin.setting_raw_chars is defined %}
      - MAX_CHARS={{ role_regards_stack_cots.phppgadmin.setting_raw_chars }}
{% endif %}
{% if role_regards_stack_cots.phppgadmin.setting_main_theme is defined %}
      - MAIN_THEME={{ role_regards_stack_cots.phppgadmin.setting_main_theme }}
{% endif %}
{% if role_regards_stack_cots.phppgadmin.setting_sidebar_left_width is defined %}
      - SIDEBAR_LEFT_WIDTH={{ role_regards_stack_cots.phppgadmin.setting_sidebar_left_width }}
{% endif %}
{% endif %}
{% if role_regards_stack_cots.phppgadmin.http is defined %}
    ports:
      - "{{ role_regards_stack_cots.phppgadmin.http }}:8080"
{% endif %}
    volumes:
{% if role_regards_stack_cots.phppgadmin.get("legacy", false) == false %}
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/lib/nginx/logs/
{% else %}
      - type: tmpfs
        target: /run/lock/apache2/
      - type: tmpfs
        target: /run/apache2/
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/lib/php5/sessions/
{% endif %}
    logging:
{% if role_regards_stack_cots.phppgadmin.logging is defined %}
      {{ role_regards_stack_cots.phppgadmin.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}
