version: '3.7'
services:

{% if role_regards_stack_cots.rabbitmq is defined %}
  rs-rabbitmq:
    image: {{ role_regards_stack_registry }}/regards-messaging:{{ role_regards_stack_cots.rabbitmq.tag | default("latest") }}
    user: "{{role_regards_stack_container_run_uid}}:{{role_regards_stack_container_run_gid}}"
    hostname: rs-rabbitmq
    volumes:
{% if role_regards_stack_cots_configuration_use_ungranular_workspace_on_workdir_network %}
      - {{ role_regards_stack_workdir_network }}:/share
{% else %}
      - {{ role_regards_stack_workspace_local }}rabbitmq:/var/lib/rabbitmq/mnesia/
{% endif %}
      - {{ role_regards_stack_config }}rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - {{ role_regards_stack_docker_network_name }}
{% if role_regards_stack_cots_configuration_use_ungranular_workspace_on_workdir_network %}
    environment:
      - RABBITMQ_MNESIA_DIR=/share/{{ role_regards_stack_stack_name }}/workspace/rabbitmq/$RABBITMQ_NODENAME
{% endif %}
{% if role_regards_stack_cots.rabbitmq.http is defined or role_regards_stack_cots.rabbitmq.client is defined %}
    ports:
{% if role_regards_stack_cots.rabbitmq.client is defined %}
      - "{{ role_regards_stack_cots.rabbitmq.client }}:5672"
{% endif %}
{% if role_regards_stack_cots.rabbitmq.http is defined %}
      - "{{ role_regards_stack_cots.rabbitmq.http }}:15672"
{% endif %}
{% endif %}
{% if role_regards_stack_attach_cots_to_specific_node|bool %}
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == {{ hostvars[groups.rabbitmq[0]].ansible_host }}]
{% endif %}
{% endif %}
