version: '3.7'

volumes:
  data-s3-minio-datavolume:
    driver: local
    driver_opts:
{% if role_regards_stack_volume_s3_minio_data.nfs is defined %}
{% for nfs_server in role_regards_stack_top_level_nfs_servers %}
{% if nfs_server.name == role_regards_stack_volume_s3_minio_data.nfs %}
      type: {{ nfs_server.config.get('type', 'nfs') }}
      o: "{{ nfs_server.config.o }}"
      device: "{{ nfs_server.config.device_prefix }}{{ role_regards_stack_volume_s3_minio_data.get('device_postfix', 's3-minio/') }}"
{% endif %}
{% endfor %}
{% else %}
      type: none
      o: bind
      device: {{ role_regards_stack_workspace_local }}s3-minio/
{% endif %}

services:
  rs-s3-minio:
    image: {{ role_regards_stack_registry }}/regards-s3-minio:{{ role_regards_stack_cots.s3_minio.tag | default("latest") }}
    user: "{{ role_regards_stack_container_run_uid }}:{{ role_regards_stack_container_run_gid }}"
    hostname: rs-s3-minio
    read_only: true
    networks:
      - {{ role_regards_stack_docker_network_name }}
{% if role_regards_stack_cots.s3_minio.client is defined or role_regards_stack_cots.s3_minio.admin is defined %}
    ports:
{% if role_regards_stack_cots.s3_minio.admin is defined %}
      - "{{ role_regards_stack_cots.s3_minio.admin }}:9001"
{% endif %}
{% if role_regards_stack_cots.s3_minio.client is defined %}
      - "{{ role_regards_stack_cots.s3_minio.client }}:9000"
{% endif %}
{% endif %}
    volumes:
      - type: volume
        source: data-s3-minio-datavolume
        target: /data
      - type: tmpfs
        target: /.minio
{% if role_regards_stack_cots.s3_minio.client is defined %}
    environment:
      - "MINIO_SERVER_URL={{ role_regards_stack_minio_public_url }}:{{ role_regards_stack_cots.s3_minio.client }}"
{% endif %}
{% if role_regards_stack_cots.s3_minio.node_label_placement_constraint is defined %}
    deploy:
      placement:
        constraints:
          - node.labels.{{ role_regards_stack_cots.s3_minio.node_label_placement_constraint.key }} == {{ role_regards_stack_cots.s3_minio.node_label_placement_constraint.value }}
{% endif %}
{% if role_regards_stack_initialize_default_logging|bool or role_regards_stack_cots.s3_minio.logging is defined %}
    logging:
{% if role_regards_stack_cots.s3_minio.logging is defined %}
      {{ role_regards_stack_cots.s3_minio.logging | to_nice_yaml | indent(6) }}
{% else %}
      options:
        max-size: "10m"
        max-file: "10"
{% endif %}
{% endif %}
