---
- name: Create mc CA trust folder
  ansible.builtin.file:
    dest: "{{ role_regards_minio_mc_loc_ca_dir }}"
    state: directory
    mode: '2770'
    owner: "{{ role_regards_minio_ssl_local_container_root_user }}"
    group: "{{ role_regards_minio_ssl_local_container_root_group }}"
    setype: "{{ role_regards_minio_ssl_local_setype }}"
    seuser: "{{ role_regards_minio_ssl_local_seuser }}"

- name: Copy mc CA trust certificate
  ansible.builtin.copy:
    src: "{{ role_regards_minio_ssl_location_inside_playbook }}{{ role_regards_minio_mc_loc_ca }}"
    dest: "{{ role_regards_minio_mc_loc_ca_dir }}/{{ role_regards_minio_mc_loc_ca }}"
    mode: '0440'
    owner: "{{ role_regards_minio_ssl_local_container_root_user }}"
    group: "{{ role_regards_minio_ssl_local_container_root_group }}"
    setype: "{{ role_regards_minio_ssl_local_setype }}"
    seuser: "{{ role_regards_minio_ssl_local_seuser }}"
