---
role_regards_fluentd_config_is_defined: "{{ group_docker_cots.fluent is defined }}"
role_regards_fluentd_config_conf_local: "{{ group_workdir_local }}{{ group_stack_name }}/config/fluentd/"

role_regards_fluentd_config_container_root_user: "{{ group_container_root_user }}"
role_regards_fluentd_config_container_root_group: "{{ group_container_root_group }}"
role_regards_fluentd_config_setype: "{{ group_setype }}"
role_regards_fluentd_config_seuser: "{{ group_seuser }}"

role_regards_fluentd_config_workers: "{{ group_docker_workers | default([]) }}"
