---
- name: Generate haproxy stack file
  ansible.builtin.template:
    src: haproxy.yml
    dest: "{{ role_regards_stack_haproxy_stack }}"
    mode: '0740'
    owner: "{{ role_regards_stack_haproxy_container_root_user }}"
    group: "{{ role_regards_stack_haproxy_container_root_group }}"
  when: role_regards_stack_haproxy_cots.haproxy is defined
