---
- name: Create rabbitMQ workingdir folder
  ansible.builtin.file:
    path: "{{ role_regards_rabbitmq_workspace_local }}rabbitmq"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_rabbitmq_container_run_user }}"
    group: "{{ role_regards_rabbitmq_container_run_group }}"
    setype: "{{ role_regards_rabbitmq_setype }}"
    seuser: "{{ role_regards_rabbitmq_seuser }}"

- name: Create rabbitMQ config folder
  ansible.builtin.file:
    dest: "{{ role_regards_rabbitmq_conf_local }}"
    state: directory
    mode: '0555'
    owner: "{{ role_regards_rabbitmq_container_run_user }}"
    group: "{{ role_regards_rabbitmq_container_run_group }}"
    setype: "{{ role_regards_rabbitmq_setype }}"
    seuser: "{{ role_regards_rabbitmq_seuser }}"

- name: Create RabbitMQ definitions config file
  ansible.builtin.copy:
    dest: "{{ role_regards_rabbitmq_conf_local }}/definitions.json"
    content: "{{ role_regards_rabbitmq_definition | to_nice_json }}"
    mode: '0555'
    owner: "{{ role_regards_rabbitmq_container_run_user }}"
    group: "{{ role_regards_rabbitmq_container_run_group }}"
    setype: "{{ role_regards_rabbitmq_setype }}"
    seuser: "{{ role_regards_rabbitmq_seuser }}"

- name: Generate RabbitMQ config file
  ansible.builtin.template:
    src: "rabbitmq.conf"
    dest: "{{ role_regards_rabbitmq_conf_local }}/rabbitmq.conf"
    mode: '0555'
    owner: "{{ role_regards_rabbitmq_container_run_user }}"
    group: "{{ role_regards_rabbitmq_container_run_group }}"
    setype: "{{ role_regards_rabbitmq_setype }}"
    seuser: "{{ role_regards_rabbitmq_seuser }}"
