- include_tasks: setup-users.yml
  when: role_setup_enable_setup_regards_users

- name: Reload sysctl settings
  become: yes
  shell: "sysctl -p"

- name: Get the username running the deploy on the target server
  command: whoami
  changed_when: false
  become: false
  register: role_setup_ansible_user

- name: Appending regards groups to user
  become: yes
  user:
    name: "{{ role_setup_ansible_user.stdout }}"
    groups: "{{ role_setup_container_root_group }},{{ role_setup_container_run_group }}"
    append: yes
  when: role_setup_enable_setup_regards_users

- name: Appending docker group to user
  become: yes
  user:
    name: "{{ role_setup_ansible_user.stdout }}"
    groups: "docker"
    append: yes

- name: Allows some user to use docker cli
  become: yes
  user:
    name: "{{ user_allowed_to_use_docker_cli }}"
    groups: "docker"
    append: yes
  loop: "{{ role_setup_external_users_allowed_to_use_docker_cli }}"
  loop_control:
    loop_var: user_allowed_to_use_docker_cli

# reload user groups, especially useful for docker
- name: reset ssh connection - if you using a local connection to perform install - YOU MUST LOGOUT & LOGIN AGAIN in order to refresh the group and add the Docker group to your current user
  meta: reset_connection
