- name: Create regards admin group. When this task fails, it can means you should not create by yourself the group and set group_enable_setup_regards_users to false
  become: yes
  group:
    name: "{{ role_setup_container_root_group }}"
    state: present
    gid: 1040
    #FIXME

- name: Create regards user group
  become: yes
  group:
    name: "{{ role_setup_container_run_group }}"
    state: present
    gid: "{{ role_setup_regards_user_gid }}"

- name: Create regards user
  become: yes
  user:
    name: "{{ role_setup_container_run_user }}"
    uid: "{{ role_setup_regards_user_uid }}"
    group: "{{ role_setup_container_run_group }}"
