---
- name: Create postgresql folder
  ansible.builtin.file:
    path: "{{ role_regards_postgres_workspace_local_workspace_local }}postgresql"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_postgres_workspace_local_container_run_user }}"
    group: "{{ role_regards_postgres_workspace_local_container_run_group }}"
    setype: "{{ role_regards_postgres_workspace_local_setype }}"
    seuser: "{{ role_regards_postgres_workspace_local_seuser }}"

- name: Set kernel.shmmax to sysctl for Ref
  sysctl:
    name: kernel.shmmax
    value: "100663296"
    sysctl_file: /etc/sysctl.d/56-regards-ref.conf
    reload: true
