---
- name: Create loki folder
  ansible.builtin.file:
    path: "{{ role_regards_loki_workspace_local_workspace_local }}loki"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_loki_workspace_local_container_run_user }}"
    group: "{{ role_regards_loki_workspace_local_container_run_group }}"
    setype: "{{ role_regards_loki_workspace_local_setype }}"
    seuser: "{{ role_regards_loki_workspace_local_seuser }}"
