#
# Copyright 2018-2020, CS GROUP – France, http://www.c-s.fr
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
- include_tasks: redhat/packages-tasks.yml
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: debian/packages-tasks.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install python3 dependencies using pip 
  pip:
    name: 
      - docker>5.0.2
      # Python Docker Swarm dependencies
      # - pyyaml
      # Update Ansible dep jinja2 (and markupsafe) to its last version
      - jinja2~=2.11
      - markupsafe~=1.0
    state: latest
    executable: "{{ role_install_modules_pip_cli }}"
    umask: "0022"
  environment:
    PIP_INDEX_URL: "{{ role_install_modules_pip_index_url }}"
    PIP_TRUSTED_HOST: "{{ role_install_modules_pip_trusted_host }}"
    HTTP_PROXY: "{{ role_install_modules_pip_http_proxy }}"
    HTTPS_PROXY: "{{ role_install_modules_pip_https_proxy }}"
    NO_PROXY: "{{ role_install_modules_pip_no_proxy }}"
  when: python_version == 3

- name: Install python2 dependencies using pip 
  pip:
    name: 
      # Only version useable with python >=2.7
      # See https://docs.ansible.com/ansible/latest/collections/community/docker/docsite/scenario_guide.html#ansible-collections-community-docker-docsite-scenario-guide
      - docker==4.4.4
      # Sometimes it installs an incompatible version (that uses python3 stuff)
      - websocket-client==0.56.0
      # Update Ansible dep jinja2 (and markupsafe) to its last version
      - jinja2~=2.11
      - markupsafe~=1.0
      - requests==2.27.1
      - certifi<=2020.4.5.1
    state: latest
    executable: "{{ role_install_modules_pip_cli }}"
    umask: "0022"
  environment:
    PIP_INDEX_URL: "{{ role_install_modules_pip_index_url }}"
    PIP_TRUSTED_HOST: "{{ role_install_modules_pip_trusted_host }}"
    HTTP_PROXY: "{{ role_install_modules_pip_http_proxy }}"
    HTTPS_PROXY: "{{ role_install_modules_pip_https_proxy }}"
    NO_PROXY: "{{ role_install_modules_pip_no_proxy }}"
  when: python_version == 2

# We're stuck with pyc files not readable by everyone, even with umask defined.
# Looks like pyc files are generated outside umask definition ????
# So we decided to make them readeable by everyone using chmod
- name: "Get the {{ role_install_modules_pip_cli }} package path"
  shell: "{{ role_install_modules_pip_cli }} show docker | grep Location | cut -d ' ' -f 2"
  register: python_package_path

- name: "Ensure pyc files inside {{ python_package_path.stdout }} are x55"
  command: find {{ python_package_path.stdout }} -type f -name "*.pyc" -exec chmod g+rx,o+rx {} \;
