{{/*
###################################################################
#                                                                 #
#   Create a deployment for a single container.                   #
#   For multiple containers you will need a different template.   #
#                                                                 #
###################################################################
*/}}
{{- define "regards-common.deployment" -}}

{{/*
Helm template magic:
Allow each chart depending on the common chart to
override the common values with its own values.
*/}}
{{- $common := dict "Values" (get .Values "regards-common") -}}
{{- $noCommon := omit .Values "regards-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}

{{/*
Now the template.
*/}}
apiVersion: apps/v1
kind: Deployment
{{ template "regards-common.metadata" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "regards-common.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels:
        {{- include "regards-common.selectorLabels" . | nindent 8 }}
    spec:
    {{- if or .Values.imagePullSecrets .Values.global.regards.imagePullSecrets }}
      imagePullSecrets:
        {{- include "regards-common.image-pull-secret-list" . | nindent 8 }}
    {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      serviceAccountName: {{ include "regards-common.serviceAccountName" . }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if hasKey .Values "initContainers" }}
      initContainers:
      {{- range (get .Values "initContainers") }}
        {{- with merge (omit $ "Values") (dict "Values" .) $common }}
        - name: {{ .Values.name }}
          image: {{ template "regards-common.image" . }}
          imagePullPolicy: {{ template "regards-common.imagePullPolicy" . }}
        {{- with .Values.entrypointOverride }}
          command:
            - "/bin/bash"
          args:
            - "-c"
            - "{{ template "regards-common.entrypoint-override" . }}"
        {{- end }}
        {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- include "regards-common.containerVolumeMounts" . | nindent 12 }}
        {{- end }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- end }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "regards-common.image" . }}
          imagePullPolicy: {{ template "regards-common.imagePullPolicy" . }}
        {{- with .Values.entrypointOverride }}
          command:
            - "/bin/bash"
          args:
            - "-c"
            - "{{ template "regards-common.entrypoint-override" . }}"
        {{- end }}
        {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- include "regards-common.containerVolumeMounts" . | nindent 12 }}
        {{- end }}
        {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.volumes }}
      volumes:
        {{- include "regards-common.podVolumes" . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end -}}
{{- end -}}