{{/*
Create a command and args if an entrypointOverride is defined
*/}}
{{- define "regards-common.entrypoint-override" -}}
{{- $startCommand := .startCommand -}}
{{- $iter := "" -}}
{{- range .waitForIts }}
  {{- $iter = printf "%s/wait-for-it.sh %s:%s -t %s -- " $iter .host (toString .port) (toString .timeout) -}}
{{- end }}
{{- printf "%s %s" $iter $startCommand -}}
{{- end -}}