{{/*
############################################################################
#                                                                          #
#   Create pod image pull secrets as per their Values configuration.       #
#                                                                          #
############################################################################
*/}}

{{/*
Create a list of fully qualified names for image pull secrets.
*/}}
{{- define "regards-common.image-pull-secret-list" -}}
{{- $imagePullSecrets := default .Values.global.regards.imagePullSecrets .Values.imagePullSecrets -}}
{{- range $index, $item := $imagePullSecrets }}
{{- $customScope := (dict "Release" (dict "Name" $.Release.Name) "imagePullSecret" (index $imagePullSecrets $index)) -}}
  - name: {{ include "regards-common.image-pull-secret" $customScope }}
{{- print "\n" }}
{{- end }}
{{- end -}}

{{/*
Create image pull secrets secret objects.
*/}}
{{- define "regards-common.image-pull-secret-secrets" -}}
{{- $imagePullSecrets := default .Values.global.regards.imagePullSecrets .Values.imagePullSecrets -}}
{{- range $index, $item := $imagePullSecrets -}}
{{- $customScope := (dict "Release" (dict "Name" $.Release.Name) "imagePullSecret" (index $imagePullSecrets $index)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regards-common.image-pull-secret" $customScope }}
  labels:
    {{- include "regards-common.selectorLabels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" $item }}
{{ printf "\n---" }}
{{- end -}}
{{- end -}}

{{/*
Create a fully qualified name for an image pull secret.
*/}}
{{- define "regards-common.image-pull-secret" -}}
{{- printf "%s-%s" .Release.Name .imagePullSecret.name | trunc 63 | trimSuffix "-" -}}
{{- end -}}



{{/*
  Generate the .dockerconfigjson file unencoded.
*/}}
{{- define "dockerconfigjson.b64dec" }}
  {{- print "{\"auths\":{" }}
  {{- range $index, $item := .credentials }}
    {{- if $index }}
      {{- print "," }}
    {{- end }}
    {{- printf "\"%s\":{\"auth\":\"%s\"}" $item.registry (printf "%s:%s" $item.username $item.accessToken | b64enc) }}
  {{- end }}
  {{- print "}}" }}
{{- end }}

{{/*
  Generate the base64-encoded .dockerconfigjson.
*/}}
{{- define "dockerconfigjson.b64enc" }}
  {{- include "dockerconfigjson.b64dec" . | b64enc }}
{{- end }}
