{{/*
############################################################################
#                                                                          #
#   Create pod volumes and mounts as per their Values configuration.       #
#   For possible volume types check                                        #
#   https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes  #
#                                                                          #
############################################################################
*/}}

{{/*
Create pod volumes configuration
*/}}
{{- define "regards-common.podVolumes" -}}
{{- with .configmaps }}
{{- include "regards-common.configMapPodVolumes" . }}
{{- end }}
{{- with .emptydirs }}
{{- include "regards-common.emptyDirPodVolumes" . }}
{{- end }}
{{- with .secrets }}
{{- include "regards-common.secretPodVolumes" . }}
{{- end }}
{{- with .persistentVolumeClaims }}
{{- include "regards-common.persistentVolumeClaimPodVolumes" . }}
{{- end }}
{{- end -}}

{{/*
Create container volume mounts matching "regards-common.containerVolumes"
as per their Values configuration.
*/}}
{{- define "regards-common.containerVolumeMounts" -}}
{{- with .configmaps }}
{{- include "regards-common.configMapContainerVolumeMounts" . }}
{{- end }}
{{- with .emptydirs }}
{{- include "regards-common.emptyDirContainerVolumeMounts" . }}
{{- end }}
{{- with .secrets }}
{{- include "regards-common.secretContainerVolumeMounts" . }}
{{- end }}
{{- with .persistentVolumeClaims }}
{{- include "regards-common.persistentVolumeClaimContainerVolumeMounts" . }}
{{- end }}
{{- end -}}

{{/*
Pod volume configuration for type configMap
*/}}
{{- define "regards-common.configMapPodVolumes" -}}
{{- range . }}
- name: {{ .name }}
  configMap:
    name: {{ .name }}
{{- end }}
{{- end -}}

{{/*
Pod volume configuration for type emptyDir
*/}}
{{- define "regards-common.emptyDirPodVolumes" -}}
{{- range . }}
- name: {{ .name }}
  emptyDir:
    medium: {{ default "" .medium }}
    sizeLimit: {{ default nil .sizeLimit }}
{{- end }}
{{- end -}}

{{/*
Pod volume configuration for type secret
*/}}
{{- define "regards-common.secretPodVolumes" -}}
{{- range . }}
- name: {{ .name }}
  secret:
    secretName: {{ .name }}
{{- end }}
{{- end -}}

{{/*
Pod volume configuration for type persistentVolumeClaim
*/}}
{{- define "regards-common.persistentVolumeClaimPodVolumes" -}}
{{- range . }}
- name: {{ .name }}
  persistentVolumeClaim:
    claimName: {{ .name }}
{{- end }}
{{- end -}}

{{/*
Container volume mount configuration for type configMap
*/}}
{{- define "regards-common.configMapContainerVolumeMounts" -}}
{{- range . }}
- name: {{ .name }}
  mountPath: {{ .mountPath }}
{{- if .subPath }}
  subPath: {{ .subPath }}
{{- end }}
{{- end }}
{{- end -}}

{{/*
Container volume mount configuration for type emptyDir
*/}}
{{- define "regards-common.emptyDirContainerVolumeMounts" -}}
{{- range . }}
- name: {{ .name }}
  mountPath: {{ .mountPath }}
{{- end }}
{{- end -}}

{{/*
Container volume mount configuration for type secret
*/}}
{{- define "regards-common.secretContainerVolumeMounts" -}}
{{- range . }}
- name: {{ .name }}
  mountPath: {{ .mountPath }}
{{- end }}
{{- end -}}


{{/*
Container volume mount configuration for type persistentVolumeClaim
*/}}
{{- define "regards-common.persistentVolumeClaimContainerVolumeMounts" -}}
{{- range . }}
- name: {{ .name }}
  mountPath: {{ .mountPath }}
{{- if .subPath }}
  subPath: {{ .subPath }}
{{- end }}
{{- end }}
{{- end -}}
