---
- name: Create REGARDS Workers root directories
  ansible.builtin.file:
    path: "{{ role_regards_workers_root_dir }}/{{ item.name }}"
    state: directory
    mode: '0750'
    owner: "{{ role_regards_workers_container_root_user }}"
    group: "{{ role_regards_workers_container_root_group }}"
    setype: "{{ role_regards_workers_setype }}"
    seuser: "{{ role_regards_workers_seuser }}"
  with_items: "{{ role_regards_workers }}"

- name: Create REGARDS Workers logs directories
  ansible.builtin.file:
    path: "{{ role_regards_workers_root_dir }}/{{ item.name }}/logs"
    state: directory
    mode: '0750'
    owner: "{{ role_regards_workers_container_run_user }}"
    group: "{{ role_regards_workers_container_run_group }}"
    setype: "{{ role_regards_workers_setype }}"
    seuser: "{{ role_regards_workers_seuser }}"
  with_items: "{{ role_regards_workers }}"

- name: Iterate over workers configuration to initialize volumes
  ansible.builtin.include_tasks: createWorkerVolumes.yml
  loop: "{{ role_regards_workers }}"
  loop_control:
    loop_var: worker
