---
- name: Create reverse proxy folder
  ansible.builtin.file:
    path: "{{ role_regards_front_conf_local }}"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
    setype: "{{ role_regards_front_setype }}"
    seuser: "{{ role_regards_front_seuser }}"

- name: Generate reverse proxy config file (legacy)
  ansible.builtin.template:
    src: "{{ role_regards_front_nginx_conf_unsecure }}.unsecure"
    dest: "{{ role_regards_front_nginx_target_conf_unsecure }}"
    mode: '0770'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
  when: role_regards_front_securised|bool == False

- name: Generate reverse proxy config file (securised)
  ansible.builtin.template:
    src: "nginx.conf"
    dest: "{{ role_regards_front_conf_local }}nginx.conf"
    mode: '0770'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
  when: role_regards_front_securised|bool

- name: Generate REGARDS config file (securised)
  ansible.builtin.template:
    src: "{{ role_regards_front_nginx_conf }}"
    dest: "{{ role_regards_front_nginx_target_conf }}"
    mode: '0770'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
  when: role_regards_front_securised|bool

- name: Generate REGARDS badhost config file (securised)
  ansible.builtin.template:
    src: "{{ role_regards_front_nginx_badhost_conf }}"
    dest: "{{ role_regards_front_nginx_target_badhost_conf }}"
    mode: '0770'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
  when: role_regards_front_securised|bool and role_regards_front_is_ssl_defined|bool

- name: Generate REGARDS RabbitMQ reverse proxy config file
  ansible.builtin.template:
    src: rabbitmq.conf
    dest: "{{ role_regards_front_conf_local }}rabbitmq.conf"
    mode: '0770'
    owner: "{{ role_regards_front_container_root_user }}"
    group: "{{ role_regards_front_container_root_group }}"
  when: role_regards_front_has_rabbitmq_admin|bool
