---
  - name: Create reverse proxy folder
    file:
      path: "{{ item }}"
      state: directory
      mode: '2750'
      owner: "{{ role_regards_front_container_root_user }}"
      group: "{{ role_regards_front_container_root_group }}"
      setype: "{{ role_regards_front_setype }}"
      seuser: "{{ role_regards_front_seuser }}"
    with_items:
      - "{{ role_regards_front_conf_local }}"
