---
  - name: "[helm/{{ bms_ms_name }}] Generate postgresql config templates"
    include_role:
      name: regards-postgres
      tasks_from: config
    vars:
      role_regards_postgres_conf_local: "{{ output_dir }}/{{ bms_ms_name }}/config/"
      role_regards_postgres_container_run_user: "{{ ansible_user }}"
      role_regards_postgres_container_run_group: "{{ ansible_user }}"
      role_regards_postgres_nb_connections: "{{ '{{' }} .Values.nbConnections {{ '}}' }}"
      group_config_mservices:
        init_project: "{{ '{{' }} default .Values.global.regards.initProject .Values.regards.initProject {{ '}}' }}"

  - name: "[helm/{{ bms_ms_name }}] Generate default values"
    ansible.builtin.template:
      src: "{{ role_path }}/charts/{{ bms_ms_name }}/{{ template_file }}"
      dest: "{{ output_dir }}/{{ bms_ms_name }}/{{ template_file }}"
    vars:
      role_regards_postgres_nb_connections: 185
      initdb_script_configmap_name: "rs-postgres-initdb"
      override_conf_configmap_name: "rs-postgres-config"
    with_items:
      - Chart.yaml
      - values.yaml
    loop_control:
      loop_var: template_file
