apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mapproxy.fullname" . }}-cache-pvc
  labels:
    {{- include "mapproxy.selectorLabels" . | nindent 4 }}
    helm.sh/chart: {{ include "mapproxy.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}