---
role_regards_front_is_defined: "{{ group_docker_mservices.front is defined }}"
# NGINX Workspace
role_regards_front_conf_local: "{{ group_workdir_local }}{{ group_stack_name }}/config/regards/nginx/"

# NGINX configuration file (legacy)
role_regards_front_nginx_conf_unsecure: "{{ group_docker_mservices.front.nginx_conf | default('nginx.conf') }}"
role_regards_front_nginx_target_conf_unsecure: "{{ role_regards_front_conf_local }}nginx.conf"

# NGINX main configuration file for dynamic modules
role_regards_front_dynamic_modules: "{{ group_docker_mservices.front.dynamic_modules | default([]) }}"

# NGINX configuration file
role_regards_front_nginx_conf: "{{ group_docker_mservices.front.nginx_conf | default('regards.conf') }}"
role_regards_front_nginx_target_conf: "{{ role_regards_front_conf_local }}regards.conf"

# NGINX configuration file
role_regards_front_nginx_badhost_conf: badhost.conf
role_regards_front_nginx_target_badhost_conf: "{{ role_regards_front_conf_local }}badhost.conf"

# Docker user
role_regards_front_container_root_user: "{{ group_container_root_user }}"
role_regards_front_container_root_group: "{{ group_container_root_group }}"
role_regards_front_setype: "{{ group_setype }}"
role_regards_front_seuser: "{{ group_seuser }}"

# Vars for config file
role_regards_front_public_server_port: "{{ group_docker_mservices.front.public_port | default(group_docker_mservices.front.port) }}"
# Gateway URI to address when using regards-front reverse proxy
gateway_default:
  # We use tasks.<service name> to retrieve a different IP than just <service name>
  # see https://forums.docker.com/t/no-route-to-host-when-contained-proxys-target-is-on-other-node-of-swarm/42526/2
  # avoid "failed (113: No route to host) while connecting to upstream" in NGinx logs
  host: tasks.rs-gateway
  http: 9030
role_regards_gateway_uri: "{{ group_docker_mservices.gateway.host | default(gateway_default.host) }}:{{ group_docker_mservices.gateway.http | default(gateway_default.http) }}"
role_regards_dns_resolver: "127.0.0.11"

role_regards_front_is_ssl_defined: "{{ group_docker_mservices.front.ssl is defined }}"

role_regards_front_server_name: "{{ group_docker_mservices.front.nginx_server_name | default(group_docker_mservices.front.host) }}"

role_regards_front_securised: "{{ group_docker_mservices.front.securised | default(True) }}"
role_regards_front_has_rabbitmq_admin: "{{ (group_docker_mservices.front | default({})).rabbitmq_admin is defined }}"
