---

- name: Add script file
  template:
    src: update-indices.sh
    dest: /tmp/update-indices.sh
    mode: '0750'
    owner: "{{ role_regards_elasticsearch_sidecar_container_root_user }}"
    group: "{{ role_regards_elasticsearch_sidecar_container_root_group }}"
  become: true

- name: Run container to updates ES settings 
  docker_container:
    name: "postinstall-elasticsearch"
    image: "{{ role_regards_elasticsearch_sidecar_registry }}/regards-bash"
    pull: true
    command: bash /update-indices.sh
    detach: false
    network_mode: "{{ role_regards_elasticsearch_sidecar_docker_network_name }}"
    networks_cli_compatible: true
    read_only: true
    cleanup: true
    networks:
      - name: "{{ role_regards_elasticsearch_sidecar_docker_network_name }}"
    volumes:
      - /tmp/update-indices.sh:/update-indices.sh
  vars:
    ansible_python_interpreter: "env python{{ python_version }}"

- name: Delete script file
  file:
    path: /tmp/update-indices.sh
    state: absent
  become: true
