---
- name: Add tmp files to /tmp/
  ansible.builtin.template:
    src: start.sh
    dest: /tmp/start.sh
    mode: '0750'
    owner: "{{ role_regards_elasticsearch_postinstall_container_root_user }}"
    group: "{{ role_regards_elasticsearch_postinstall_container_root_group }}"
  become: true
  when: role_regards_elasticsearch_postinstall_elasticsearch_active|bool

- name: Run container to updates ES settings 
  docker_container:
    name: postinstall-elasticsearch
    validate_certs: "{{ role_regards_elasticsearch_postinstall_validate_certs }}"
    image: "{{ role_regards_elasticsearch_postinstall_registry }}/regards-bash:{{ role_regards_elasticsearch_postinstall_image_version }}"
    pull: true
    command: bash /start.sh
    detach: false
    network_mode: none
    networks_cli_compatible: true
    read_only: true
    cleanup: true
    # container_default_behavior: no_defaults
    log_driver: json-file
    networks:
      - name: "{{ role_regards_elasticsearch_postinstall_docker_network_name }}"
    volumes:
      - /tmp/start.sh:/start.sh
  vars:
    ansible_python_interpreter: "env python{{ python_version }}"
  when: role_regards_elasticsearch_postinstall_elasticsearch_active|bool

- name: Delete tmp files
  ansible.builtin.file:
    path: /tmp/start.sh
    state: absent
  become: true
  when: role_regards_elasticsearch_postinstall_elasticsearch_active|bool
