---
- name: Add audit rules
  become: yes
  lineinfile:
    path: "/etc/audit/rules.d/audit.rules"
    line: "{{ item }}"
  with_items:
    - "-w /usr/bin/docker -p rxwa -k docker"
    - "-w /var/lib/docker -p wa -k docker"
    - "-w /etc/docker -p wa -k docker"
    - "-w /usr/lib/systemd/system/docker.service -p wa -k docker"
    - "-w /usr/lib/systemd/system/docker.socket -p wa -k docker"
    - "-w /etc/docker/daemon.json -p wa -k docker"
    - "-w /usr/bin/dockerd -p wa -k docker"
  notify:
    - Generate auditd rules
