---
# Stack infos
role_regards_stack_haproxy_stack_name: "{{ group_stack_name }}"

# Folder structure
role_regards_stack_haproxy_config: "{{ group_workdir_local }}{{ group_stack_name }}/config/"
role_regards_stack_haproxy_stack: "{{ group_workdir_local }}{{ group_stack_name }}/stack/"

# Files owners
role_regards_stack_haproxy_container_root_user: "{{ group_container_root_user }}"
role_regards_stack_haproxy_container_root_group: "{{ group_container_root_group }}"

# Docker users
role_regards_stack_haproxy_container_run_uid: "{{ group_container_run_uid }}"
role_regards_stack_haproxy_container_run_gid: "{{ group_container_run_gid }}"

# Docker conf
role_regards_stack_haproxy_docker_network_name: "{{ group_docker_network_name }}"
role_regards_stack_haproxy_registry: "{{ group_docker_registry }}"

# COTS
role_regards_stack_haproxy_cots: "{{ group_docker_cots }}"
# Optional Kibana
role_regards_stack_haproxy_cots_elasticsearch: "{{  group_docker_cots.get('elasticsearch', {}) }}"
role_regards_stack_haproxy_cots_haproxy: "{{  group_docker_cots.get('elasticsearch', {}) }}"

# Resource limits
role_regards_stack_haproxy_enable_cots_resource_limits: "{{ (group_docker_cots_configuration | default({})).get('enable_resource_limits', false) | bool }}"

role_regards_stack_haproxy_resource_limits:
  haproxy:
    limits:
      cpus: '2'
      memory: "{{ role_regards_stack_haproxy_cots.get('haproxy', {}).get('containerLimit', '2500m') }}"
    reservations:
      cpus: '1'
      memory: "{{ role_regards_stack_haproxy_cots.get('haproxy', {}).get('memoryLimit', '2000m') }}"
