---
  - name: Init Postgres nb connections
    set_fact:
      postgres_nb_connections: 0

  - name: Iterate over microservice
    include_tasks: computeNbConnection.yml
    loop: "{{ role_regards_postgres_mservices | dict2items }}"
    loop_control:
      loop_var: mservice

  - name: Copy configuraton
    template:
      src: "{{ item }}"
      dest: "{{ role_regards_postgres_conf_local }}"
      mode: '0555'
      owner: "{{ role_regards_postgres_container_run_user }}"
      group: "{{ role_regards_postgres_container_run_group }}"
    with_items:
      - init.sql
      - postgresql.conf
