---
  - name: Copy configuraton
    template:
      src: "{{ item }}"
      dest: "{{ role_regards_postgres_conf_local }}"
      mode: '0555'
      owner: "{{ role_regards_postgres_container_run_user }}"
      group: "{{ role_regards_postgres_container_run_group }}"
    with_items:
      - init.sql
      - postgresql.conf
