---
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/init.yml"
  when: role_regards_postgres_is_defined|bool

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yml"
  when: role_regards_postgres_is_defined|bool
