---
- name: Create configs folder
  ansible.builtin.file:
    path: "{{ role_regards_mounts_secrets_configs_configs_destination }}/{{ item.path }}"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_mounts_secrets_configs_container_root_user }}"
    group: "{{ role_regards_mounts_secrets_configs_container_root_group }}"
    setype: "{{ role_regards_mounts_secrets_configs_setype }}"
    seuser: "{{ role_regards_mounts_secrets_configs_seuser }}"
  with_items: "{{ role_regards_mounts_secrets_configs_configs }}"

- name: Copy configs
  ansible.builtin.copy:
    src: "{{ role_regards_mounts_secrets_configs_inventory_path_configs }}/{{ item.path }}/{{ item.file }}"
    dest: "{{ role_regards_mounts_secrets_configs_configs_destination }}/{{ item.path }}/{{ item.file }}"
    mode: '0770'
    owner: "{{ role_regards_mounts_secrets_configs_container_root_user }}"
    group: "{{ role_regards_mounts_secrets_configs_container_root_group }}"
    setype: "{{ role_regards_mounts_secrets_configs_setype }}"
    seuser: "{{ role_regards_mounts_secrets_configs_seuser }}"
  with_items: "{{ role_regards_mounts_secrets_configs_configs }}"
