---

- name: Create fluentd folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_fluentd_container_root_user }}"
    group: "{{ role_regards_fluentd_container_root_group }}"
    setype: "{{ role_regards_fluentd_setype }}"
    seuser: "{{ role_regards_fluentd_seuser }}"
  with_items:
    - "{{ role_regards_fluentd_conf_local }}"
    - "{{ role_regards_fluentd_workspace_local_logs }}"


- name: Create logs directories
  ansible.builtin.file:
    path: "{{ role_regards_fluentd_workspace_local_logs }}{{ item }}"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_fluentd_container_run_user }}"
    group: "{{ role_regards_fluentd_container_run_group }}"
    setype: "{{ role_regards_fluentd_setype }}"
    seuser: "{{ role_regards_fluentd_seuser }}"
  with_items:
    - "{{ role_regards_fluentd_logs_directory }}"
