---
role_regards_plugin_remove_workspace_nfs_docker_network_name: "{{ group_docker_network_name }}"
role_regards_plugin_remove_workspace_nfs_registry: "{{ group_docker_registry }}"

role_regards_plugin_remove_workspace_nfs_container_root_user: "{{ group_container_root_user }}"
role_regards_plugin_remove_workspace_nfs_container_root_group: "{{ group_container_root_group }}"

role_regards_plugin_remove_workspace_nfs_validate_certs: "{{ group_validate_certs | default(lookup('ansible.builtin.env', 'DOCKER_TLS_VERIFY')|default(false, true)) }}"

role_regards_plugin_remove_workspace_nfs_image_version: "{{ (group_docker_cots.bash | default({})).get('tag', global_regards.version) }}"

role_regards_plugin_remove_workspace_nfs_container_run_user: "{{ group_container_run_user }}"
role_regards_plugin_remove_workspace_nfs_container_run_group: "{{ group_container_run_group }}"
# We're outside namespace - recompute run user and group
role_regards_plugin_remove_workspace_nfs_run_uid: "{{ group_container_run_uid|int + name_space_uid|int }}"
role_regards_plugin_remove_workspace_nfs_run_gid: "{{ group_container_run_gid|int + name_space_gid|int }}"

role_regards_plugin_remove_workspace_nfs_top_level_nfs_servers: "{{  (group_docker_mounts | default({})).get('nfs', []) }}"

role_regards_plugin_remove_workspace_nfs_active: "{{ (group_docker_mounts | default({})).get('regards', {}).get('plugins', {}).nfs is defined }}"
role_regards_plugin_remove_workspace_nfs_mount_conf: "{{ (group_docker_mounts | default({})).get('regards', {}).get('plugins', {}) }}"
