---
  - name: Create REGARDS basic structure
    file:
      path: "{{ item }}"
      state: directory
      mode: '0750'
      owner: "{{ role_regards_init_master_container_root_user }}"
      group: "{{ role_regards_init_master_container_root_group }}"
      setype: "{{ role_regards_init_master_setype }}"
      seuser: "{{ role_regards_init_master_seuser }}"
    with_items:
      - "{{ role_regards_init_master_config }}"
      - "{{ role_regards_init_master_stack }}"
      # legacy
      - "{{ role_regards_init_master_cli }}"
    become: true

  - name: Get regards network info
    docker_network_info:
      name: "{{ role_regards_init_master_docker_network_name }}"
    register: docker_network_name_info
    become: yes
    vars:
      ansible_python_interpreter: "env python{{ python_version }}"

  - name: Should recreate regards network network?
    set_fact:
      recreate_regards_network: "{{ docker_network_name_info.exists != true or docker_network_name_info.network.Driver != \"overlay\" or docker_network_name_info.network.Attachable != true or docker_network_name_info.network.IPAM.Config[0].Gateway != role_regards_init_master_docker_network_gateway or docker_network_name_info.network.IPAM.Config[0].Subnet != role_regards_init_master_docker_network_subnet }}"

  - name: Remove regards network
    docker_network:
      name: "{{ role_regards_init_master_docker_network_name  }}"
      state: absent
    become: yes
    when: recreate_regards_network|bool
    run_once: true
    ignore_errors: true
    vars:
      ansible_python_interpreter: "env python{{ python_version }}"

  - name: Create regards network (fails if the REGARDS stack is deployed)
    docker_network:
      name: "{{ role_regards_init_master_docker_network_name }}"
      attachable: true
      driver: overlay
      ipam_config:
        - subnet: "{{ role_regards_init_master_docker_network_subnet }}"
          gateway: "{{ role_regards_init_master_docker_network_gateway }}"
    vars:
      ansible_python_interpreter: "env python{{ python_version }}"
    when: recreate_regards_network|bool

  - name: Add dev CLI (legacy)
    template:
      src: "{{ item }}"
      dest: "{{ role_regards_init_master_cli }}"
      mode: '0750'
      owner: "{{ role_regards_init_master_container_root_user }}"
      group: "{{ role_regards_init_master_container_root_group }}"
    with_items:
      - status.sh
      - deploy.sh
      - update.sh
      - logs.sh
      - reboot.sh
      - exec.sh
      - health.sh
      - shutdown.sh
      - regenerate-ca.sh
    become: true

  - name: Create REGARDS basic structure
    file:
      path: "{{ role_regards_init_master_cli_system_install }}"
      state: directory
      mode: '0750'
      owner: root
      group: "{{ role_regards_init_master_container_root_group }}"
      setype: "{{ role_regards_init_master_setype }}"
      seuser: "{{ role_regards_init_master_seuser }}"
    become: true

  - name: Add dev CLI into etc
    template:
      src: "{{ item }}"
      dest: "{{ role_regards_init_master_cli_system_install }}"
      mode: '0750'
      owner: root
      group: "{{ role_regards_init_master_container_root_group }}"
    with_items:
      - status.sh
      - deploy.sh
      - update.sh
      - logs.sh
      - reboot.sh
      - exec.sh
      - health.sh
      - shutdown.sh
      - regenerate-ca.sh
    become: true
