---
role_regards_minio_workspace_local_active: "{{ group_docker_cots.minio is defined and (group_docker_mounts | default({})).get('minio', [])|length == 0 }}"

role_regards_minio_workspace_local_container_run_user: "{{ group_container_run_user }}"
role_regards_minio_workspace_local_container_run_group: "{{ group_container_run_group }}"
role_regards_minio_workspace_local_setype: "{{ group_setype }}"
role_regards_minio_workspace_local_seuser: "{{ group_seuser }}"

role_regards_minio_workspace_local_directory: "{{ group_workdir_local }}{{ group_stack_name }}/workspace/minio"
