{{/*
Helm template magic:
override the common values with this chart own values.
*/}}
{{- $common := dict "Values" (get .Values "regards-common") -}}
{{- $noCommon := omit .Values "regards-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $root := omit . "Values" -}}
{{- with merge $root $overrides $common -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-gateway-config
data:
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "config/" $key }}
  {{ $key | trimPrefix "config/" }}: |-
    {{- tpl ($files.Get $key ) $root | nindent 4 -}}
  {{- end }}
  {{- end }}
{{- end }}
