{{- template "regards-common.deployment" . -}}
{{/*
# {% if role_regards_stack_mservices.gateway is defined %}
#   # Zuul
#   rs-gateway:
#     user: "{{ role_regards_stack_container_run_uid }}:{{ role_regards_stack_container_run_gid }}"
#     hostname: rs-gateway
#     read_only: true
#     networks:
#       - {{ role_regards_stack_docker_network_name }}
#     volumes:
#       - {{ role_regards_stack_workspace_local }}regards/logs/gateway:/logs
#     logging:
#       options:
#         max-size: "10m"
#         max-file: "10"
# {% endif %}


#   # Zuul
#   rs-gateway:
#     user: "1403050:1401050"
#     hostname: rs-gateway
#     read_only: true
#     networks:
#       - regards_network_leo_3
#     volumes:
#       - /DATA/sandbox/geode/workspace/regards/logs/gateway:/logs
#     logging:
#       options:
#         max-size: "10m"
#         max-file: "10"
*/}}