---
- name: Create REGARDS basic structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ role_regards_init_network_workdir_container_root_user }}"
    group: "{{ role_regards_init_network_workdir_container_root_group }}"
    setype: "{{ role_regards_init_network_workdir_setype }}"
    seuser: "{{ role_regards_init_network_workdir_seuser }}"
  with_items:
    - "{{ role_regards_init_network_workdir_workdir_network }}"
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/storage/"
  when: role_regards_init_network_workdir_network_allow_root
  become: true

- name: Create REGARDS folders mounted inside containers on the network workspace
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '2750'
    owner: "{{ role_regards_init_network_workdir_container_run_user }}"
    group: "{{ role_regards_init_network_workdir_container_run_group }}"
    setype: "{{ role_regards_init_network_workdir_setype }}"
    seuser: "{{ role_regards_init_network_workdir_seuser }}"
  with_items:
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/storage/dam" # For DAM documents
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/storage/onlines" # For online  local storages
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/storage/cache" # For STORAGE cache
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/input" # Common input folder for dataprovider, fem, ingest and storage
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/front"
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/workspace" # Common microservices workspace directory
    - "{{ role_regards_init_network_workdir_workspace_network }}regards/processing/"
  become: true
  when: role_regards_init_network_workdir_network_allow_root
