---
- name: Iterate over NFS servers
  ansible.builtin.include_tasks: initNfs.yml
  loop: "{{ role_regards_init_nfs_workspaces_top_level_nfs_servers }}"
  # skipping NFS initialisation when we detect ro (Read only) in its config
  when: 
    - not 'ro,' in nfs_server.config.o
    - nfs_server.get('skip_init_volumes', False)|bool == False
  loop_control:
    loop_var: nfs_server
