{
 "title": "[MONITORING] Containers",
 "tags": [
  "cpu",
  "memory",
  "container",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Last time container created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(docker_container_status_started_at)/1000000000\n"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_containers_running)"
    }
   ]
  },
  {
   "title": "CPU Usage per Container type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(docker_container_cpu_usage_total{cpu=\"cpu-total\"}[1m])/1000000000) by (container_image), \"name\", \"$1\", \"container_image\", \".+[/]([0-9A-z_-]+)[:].+\")",
     "legendFormat": "{{ '{{' }}name{{ '}}' }}"
    }
   ]
  },
  {
   "title": "CPU by Container",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_total{cpu=\"cpu-total\"}[1m])/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Container type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(avg_over_time(docker_container_mem_usage[1m])) by (container_image), \"name\", \"$1\", \"container_image\", \".+[/]([0-9A-z_-]+)[:].+\")",
     "legendFormat": "{{ '{{' }}name{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(docker_container_mem_limit - docker_container_mem_usage) by (container_name)",
     "legendFormat": "{{ '{{' }}label_name{{ '}}' }}"
    },
    {
     "expr": "sum(docker_container_mem_limit) by (container_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(docker_container_mem_usage) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(docker_container_net_rx_bytes[$__rate_interval])) by (container_image), \"name\", \"$1\", \"container_image\", \".+[/]([0-9A-z_-]+)[:].+\")",
     "legendFormat": "{{ '{{' }}name{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(docker_container_net_tx_bytes[$__rate_interval])) by (container_image), \"name\", \"$1\", \"container_image\", \".+[/]([0-9A-z_-]+)[:].+\")",
     "legendFormat": "{{ '{{' }}name{{ '}}' }}"
    }
   ]
  }
 ]
}