{
 "title": "Logs",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Level",
    "query": {}
   },
   {
    "name": "swarm_service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "swarm_node",
    "label": "Host",
    "query": {}
   },
   {
    "name": "swarm_service_id",
    "label": "Service ID",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service=~\"$swarm_service\", swarm_node=~\"$swarm_node\", swarm_service_id=~\"$swarm_service_id\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\" != \"/actuator\" )[$__interval])) by (level)",
     "legendFormat": "{{ '{{' }}stream{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({swarm_service=~\"$swarm_service\", swarm_node=~\"$swarm_node\", swarm_service_id=~\"$swarm_service_id\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\" != \"/actuator\" )[$__interval]))\n\n\n\n\n\n",
     "legendFormat": "Matching logs"
    },
    {
     "expr": "sum(count_over_time(({swarm_service=~\"$swarm_service\", swarm_node=~\"$swarm_node\", swarm_service_id=~\"$swarm_service_id\", level=\"ERROR\"} |~ \"(?i)$searchable_pattern\" != \"/actuator\" )[$__interval]))",
     "legendFormat": "In error"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{swarm_service=~\"$swarm_service\", swarm_node=~\"$swarm_node\", swarm_service_id=~\"$swarm_service_id\", level=~\"$level\"} |= `$searchable_pattern` != `/actuator` | json | line_format `[{{ '{{' }}.swarm_service{{ '}}' }}]\\t[{{ '{{' }}.level{{ '}}' }}]\\t[{{ '{{' }}.file{{ '}}' }}] - {{ '{{' }}.message{{ '}}' }}{{ '{{' }}.msg{{ '}}' }}{{ '{{' }}.log{{ '}}' }}{{ '{{' }}.request{{ '}}' }} {{ '{{' }}.stack_trace{{ '}}' }}`"
    }
   ]
  }
 ]
}