{
 "title": "[COTS] MinIO",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [
  "cots",
  "minio",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds)",
     "legendFormat": "{{ '{{' }}instance{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes)",
     "legendFormat": "{{ '{{' }}instance{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum(minio_bucket_usage_total_bytes) by (instance,server))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (range) (sum (minio_bucket_objects_size_distribution) by (range))",
     "legendFormat": "{{ '{{' }}range{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (minio_node_file_descriptor_open_total)"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes)"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (minio_node_go_routine_total)"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total"
    }
   ]
  },
  {
   "title": "Total Online Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_online_total",
     "legendFormat": "Total online disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bucket) (minio_bucket_usage_total_bytes))"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes[$__rate_interval]))",
     "legendFormat": "Data Received [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes[$__rate_interval]))",
     "legendFormat": "Data Sent [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total"
    }
   ]
  },
  {
   "title": "Total Offline Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_offline_total"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_bucket_usage_object_total) by (instance))"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_heal_time_last_activity_nano_seconds",
     "legendFormat": "{{ '{{' }}server{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_usage_last_activity_nano_seconds",
     "legendFormat": "{{ '{{' }}server{{ '}}' }}"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_total[$__rate_interval]))",
     "legendFormat": "{{ '{{' }}server,api{{ '}}' }}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_errors_total[$__rate_interval]))",
     "legendFormat": "{{ '{{' }}server,api{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Bucket Traffic Sent",
   "type": "timeseries",
   "description": "Total s3 bytes sent per bucket",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_sent_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Traffic Received",
   "type": "timeseries",
   "description": "Total s3 bytes received per bucket",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_received_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total[$__rate_interval]))",
     "legendFormat": "{{ '{{' }}server,api{{ '}}' }}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total[$__rate_interval]))",
     "legendFormat": "{{ '{{' }}server,api{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Internode Data Transfer",
   "type": "graph",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{ '{{' }}server{{ '}}' }}]"
    },
    {
     "expr": "rate(minio_inter_node_traffic_received_bytes[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Healing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_heal_objects_heal_total)",
     "legendFormat": "Objects healed in current self heal run"
    },
    {
     "expr": "sum by (instance) (minio_heal_objects_error_total)",
     "legendFormat": "Heal errors in current self heal run"
    },
    {
     "expr": "sum by (instance) (minio_heal_objects_total) ",
     "legendFormat": "Objects scanned in current self heal run"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds[$__rate_interval])",
     "legendFormat": "CPU Usage Rate [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes",
     "legendFormat": "Memory Used [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_drive_used_bytes",
     "legendFormat": "Used Capacity [{{ '{{' }}server{{ '}}' }}:{{ '{{' }}disk{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Drives Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_free_inodes",
     "legendFormat": "Free Inodes [{{ '{{' }}server{{ '}}' }}:{{ '{{' }}disk{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{ '{{' }}server{{ '}}' }}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Node File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total",
     "legendFormat": "Open FDs [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes[$__rate_interval])",
     "legendFormat": "Node RChar [{{ '{{' }}server{{ '}}' }}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes[$__rate_interval])",
     "legendFormat": "Node WChar [{{ '{{' }}server{{ '}}' }}]"
    }
   ]
  }
 ]
}