{
 "title": "Nginx reverse proxy",
 "description": "Nginx access log analytics dashboard using Promtail and Loki v2+. Prometheus datasource is created from Loki service.",
 "tags": [
  "nginx",
  "loki",
  "regards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sources & Behaviours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({swarm_service=\"rs-front\"} | json  http_user_agent | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{ '{{' }} http_user_agent {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Top Requested Pages - Excluding '/'",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "topk(10,sum by (uri) (count_over_time({swarm_service=\"rs-front\"} | json uri, http_user_agent | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | uri != \"/\" | __error__=\"\" [$__interval])))\n\n\n\n\n\n",
     "legendFormat": "{{ '{{' }}uri{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Requests & HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({swarm_service=\"rs-front\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({swarm_service=\"rs-front\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({swarm_service=\"rs-front\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{swarm_service=\"rs-front\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | uri !~ \"/robots.txt\"  | line_format \"[{{ '{{' }}.status{{ '}}' }}] {{ '{{' }}.request{{ '}}' }}\""
    }
   ]
  },
  {
   "title": "Request Statistics Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{swarm_service=\"rs-front\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({swarm_service=\"rs-front\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({swarm_service=\"rs-front\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({swarm_service=\"rs-front\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}