{
 "title": "[MONITORING] Prometheus",
 "description": "Get started faster with Grafana Cloud then easily build these dashboards. https://grafana.com/products/cloud/\nOverview of metrics from Prometheus 2.0.  \nUseful for using prometheus to monitor your prometheus.\nRevisions welcome!",
 "tags": [
  "monitoring",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Uptime [2h]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent 2d period.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=~\"prometheus\"}[2h]) * 100)"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used / day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "86400*avg(rate(prometheus_tsdb_head_samples_appended_total[2h])) * avg(rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[2h])  / rate(prometheus_tsdb_compaction_chunk_samples_sum[2h]) ) without  (instance,job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds) by (job)",
     "legendFormat": "{{ '{{' }}job{{ '}}' }}"
    }
   ]
  }
 ]
}