{
 "title": "Microservice REGARDS",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [
  "jvm",
  "prometheus",
  "regards"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(process_uptime_seconds, job)"
    }
   },
   {
    "name": "replication_instance",
    "label": "Container replica",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$application-scrape\"},replication_instance)"
    }
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Tenant",
    "query": {
     "query": "label_values(hikaricp_connections{replication_instance=~\"$replication_instance\"}, pool)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (last started container)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(last_over_time(process_uptime_seconds{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time (last started container)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(process_start_time_seconds{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application-scrape\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$application-scrape\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})",
       "legendFormat": "Active connections"
      },
      {
       "expr": "sum(hikaricp_connections_idle{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})",
       "legendFormat": "Idle connections"
      },
      {
       "expr": "sum(hikaricp_connections_pending{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})",
       "legendFormat": "Pending threads"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_min{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})"
      }
     ]
    },
    {
     "title": "Connections per instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}",
       "legendFormat": "Active connections replica {{ '{{' }} replication_instance {{ '}}' }}"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}",
       "legendFormat": "Pending threads replica {{ '{{' }} replication_instance {{ '}}' }}"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})"
      }
     ]
    },
    {
     "title": "Total Timeout",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_timeout_total{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(hikaricp_connections_usage_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_usage_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval])",
       "legendFormat": "Usage time replica {{ '{{' }} replication_instance {{ '}}' }}"
      },
      {
       "expr": "irate(hikaricp_connections_creation_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_creation_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval])",
       "legendFormat": "Creation time replica {{ '{{' }} replication_instance {{ '}}' }}"
      },
      {
       "expr": "irate(hikaricp_connections_acquire_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_acquire_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", pool=~\"$hikaricp_pool_name\"}[$__rate_interval])",
       "legendFormat": "Connection acquired replica {{ '{{' }} replication_instance {{ '}}' }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring metrics - Database, Scheduler and HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Longest Scheduler",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, max (max_over_time(tasks_scheduled_execution_seconds_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(code_namespace, code_function, outcome))\n"
      },
      {
       "expr": "sum (increase(tasks_scheduled_execution_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(code_namespace, code_function, outcome)\n"
      },
      {
       "expr": "sum by(code_namespace, code_function, outcome) (\n    increase(tasks_scheduled_execution_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)\n/ \nsum by(code_namespace, code_function, outcome) (\n    increase(tasks_scheduled_execution_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)"
      }
     ]
    },
    {
     "title": "Top 10 Longest DB Requests",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, max (max_over_time(spring_data_repository_invocations_seconds_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(repository, method, state))\n"
      },
      {
       "expr": "sum (increase(spring_data_repository_invocations_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(repository, method, state)\n"
      },
      {
       "expr": "sum by(repository, method, state) (\n    increase(spring_data_repository_invocations_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)\n/ \nsum by(repository, method, state) (\n    increase(spring_data_repository_invocations_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by(exception) (increase(http_server_requests_seconds_count{exception!=\"None\", job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range]))) > 0"
      }
     ]
    },
    {
     "title": "Top 10 Longest HTTP Requests",
     "type": "table",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, max (max_over_time(http_server_requests_seconds_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(uri, outcome, method))"
      },
      {
       "expr": "sum (increase(http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])) by(uri, outcome, method)"
      },
      {
       "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[$__range])\n)"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    sum by (method, uri, exception, status) (\n        increase(\n            http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", status=~\"5..|400|499\"}[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Remaining container memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_limit{container_name=~\".+_$application.$replication_instance.+\", container_status=\"running\"} - docker_container_mem_usage{container_name=~\".+_$application.$replication_instance.+\", container_status=\"running\"}",
     "legendFormat": "remaining"
    },
    {
     "expr": "docker_container_mem_limit{container_name=~\".+_$application.$replication_instance.+\", container_status=\"running\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "{{ '{{' }}state{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])",
     "legendFormat": "{{ '{{' }}level{{ '}}' }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])",
       "legendFormat": "{{ '{{' }}action{{ '}}' }} ({{ '{{' }}cause{{ '}}' }})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])",
       "legendFormat": "avg {{ '{{' }}action{{ '}}' }} ({{ '{{' }}cause{{ '}}' }})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "max {{ '{{' }}action{{ '}}' }} ({{ '{{' }}cause{{ '}}' }})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_busy_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max_threads{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "JETTY - MAX"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{job=\"$application-scrape\",instance=~\"$instance\"}[1m])",
       "legendFormat": "delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{job=\"$application-scrape\", replication_instance=~\"$replication_instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}