{{- template "regards-common.deployment" . -}}
{{/*
  rs-storage:
    user: "{{ role_regards_stack_container_run_uid }}:{{ role_regards_stack_container_run_gid }}"
    hostname: rs-storage
    read_only: true
    networks:
      - {{ role_regards_stack_docker_network_name }}
    volumes:
      - {{ role_regards_stack_workspace_local }}regards/logs/storage:/logs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
*/}}