{{- if .Values.pluginsPersistentVolumeClaim -}}
{{- $root := . -}}
{{- $persistence := .Values.pluginsPersistentVolumeClaim -}}
{{- $overridepersistence := dict "Values" (dict "fullnameOverride" $persistence.name "persistence" $persistence) -}}
{{- with merge $overridepersistence $root -}}

{{- template "regards-common.persistent-volume-claim" . -}}

{{- end -}}
{{- end -}}