apiVersion: v2
name: regards
description: A Helm chart for REGARDS
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: {{ regards_version }}

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: {{ regards_version }}

dependencies:
- name: regards-common
  version: 0.1.0
  repository: "file://../regards-common"
- name: regards-cots
  alias: cots
  version: {{ regards_version }}
  condition: cots.enabled
  repository: "file://../regards-cots"
- name: rs-config
  alias: config
  version: {{ regards_version }}
  repository: "file://../config"
- name: rs-registry
  alias: registry
  version: {{ regards_version }}
  repository: "file://../registry"
- name: rs-admin-instance
  alias: admin-instance
  version: {{ regards_version }}
  repository: "file://../admin-instance"
- name: rs-admin
  alias: admin
  version: {{ regards_version }}
  repository: "file://../admin"
- name: rs-access-instance
  alias: access-instance
  version: {{ regards_version }}
  repository: "file://../access-instance"
- name: rs-access-project
  alias: access-project
  version: {{ regards_version }}
  repository: "file://../access-project"
- name: rs-gateway
  alias: gateway
  version: {{ regards_version }}
  repository: "file://../gateway"
- name: rs-authentication
  alias: authentication
  version: {{ regards_version }}
  repository: "file://../authentication"
- name: rs-ingest
  alias: ingest
  version: {{ regards_version }}
  repository: "file://../ingest"
- name: rs-dam
  alias: dam
  version: {{ regards_version }}
  repository: "file://../dam"
- name: rs-notifier
  alias: notifier
  version: {{ regards_version }}
  repository: "file://../notifier"
- name: rs-fem
  alias: fem
  version: {{ regards_version }}
  repository: "file://../fem"
- name: rs-catalog
  alias: catalog
  version: {{ regards_version }}
  repository: "file://../catalog"
- name: rs-order
  alias: order
  version: {{ regards_version }}
  repository: "file://../order"
- name: rs-processing
  alias: processing
  version: {{ regards_version }}
  repository: "file://../processing"
- name: rs-dataprovider
  alias: dataprovider
  version: {{ regards_version }}
  repository: "file://../dataprovider"
- name: rs-storage
  alias: storage
  version: {{ regards_version }}
  repository: "file://../storage"
- name: rs-front
  alias: front
  version: {{ regards_version }}
  repository: "file://../front"
