#jinja2: trim_blocks: True, lstrip_blocks: True
# Default values for regards.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  kibanaEnabled: false
  regards: 
    # accessMode: ReadWriteOnce
    # storageClass: "-"
    servicesVersion: "{{ regards_version }}"
    imageRegistry: "{{ group_docker_registry }}"
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: regards-docker-registry
        credentials:
          - registry: "{{ group_docker_registry }}"
            username: "{{ group_docker_registry_username }}"
            accessToken: "{{ group_docker_registry_password }}"
    configService:
      host: "{{ group_docker_mservices.config.host }}"
      port: {{ group_docker_mservices.config.http }}
    jwtSecret: "{{ group_config_mservices.jwt_secret }}"
    cipherIV: "{{ group_config_mservices.cipher_iv }}"
    initProject: "{{ group_config_mservices.init_project }}"
    instanceAdmin:
      username: "{{ group_config_mservices.instance_admin.username }}"
      password: "{{ group_config_mservices.instance_admin.password }}"
    mail:
      host: "{{ group_config_mservices.mail.host }}"
      port: {{ group_config_mservices.mail.port }}
      username: "{{ group_config_mservices.mail.username }}"
      password: "{{ group_config_mservices.mail.password }}"
      noreply: "{{ group_config_mservices.mail.noreply }}"
    proxy:
      host: "{{ group_config_mservices.proxy.host }}"
      port: {{ group_config_mservices.proxy.port }}
      no_proxy: "{{ group_config_mservices.proxy.no_proxy }}"
    eureka:
      host: "{{ group_config_mservices.eureka.host }}"
      port: {{ group_config_mservices.eureka.port }}
    elastic:
      host: "{{ group_config_mservices.elastic.host }}"
      cluster: "{{ group_config_mservices.elastic.cluster }}"
      port: {{ group_config_mservices.elastic.port }}
    postgres:
      init_project:
        host: "{{ group_config_mservices.postgres.init_project.host }}"
        port: {{ group_config_mservices.postgres.init_project.port }}
        db: "{{ group_config_mservices.postgres.init_project.db }}"
        user: "{{ group_config_mservices.postgres.init_project.user }}"
        password: "{{ group_config_mservices.postgres.init_project.password }}"
      instance:
        host: "{{ group_config_mservices.postgres.instance.host }}"
        port: {{ group_config_mservices.postgres.instance.port }}
        db: "{{ group_config_mservices.postgres.instance.db }}"
        user: "{{ group_config_mservices.postgres.instance.user }}"
        password: "{{ group_config_mservices.postgres.instance.password }}"
    amqp:
      host: "{{ group_config_mservices.amqp.host }}"
      client: {{ group_config_mservices.amqp.client }}
      http: {{ group_config_mservices.amqp.http }}
      user: "{{ group_config_mservices.amqp.user }}"
      password: "{{ group_config_mservices.amqp.password }}"
    front:
      host: "{{ group_docker_mservices.front.host }}"
      port: {{ group_docker_mservices.front.port }}
  coordinating:
    name: coordinating

cots:
  enabled: true
  postgresql:
    fullnameOverride: rs-postgres
    postgresqlUsername: "{{ group_config_mservices.postgres.instance.user }}"
    postgresqlPassword: "{{ group_config_mservices.postgres.instance.password }}"
  rabbitmq:
    fullnameOverride: rs-rabbitmq
    auth:
      username: "{{ group_config_mservices.amqp.user }}"
      password: "{{ group_config_mservices.amqp.password }}"
  elasticsearch:
    # useless with this chart, thanks bitnami...
    # fullnameOverride: rs-elasticsearch
    nameOverride: rs-elasticsearch
    master:
      replicas: 2
      name: master
    coordinating:
      replicas: 1
      name: coordinating
    data:
      replicas: 1
      name: data
    kibana:
      fullnameOverride: rs-kibana
      configuration:
        server:
          basePath: /kibana
          rewriteBasePath: true

front:
  fullnameOverride: rs-front
  env:
    - name: GATEWAY_PUBLIC_URL
    # NOTE: should be escaped: http://localhost => http\\/\\/localhost
      value: {{ group_docker_mservices.front.protocol }}:\\/\\/{{ group_docker_mservices.front.host }}:{{ group_docker_mservices.front.port }}

ingress:
  enabled: true
  rules:
  - host: {{ group_docker_mservices.front.host }}
    http:
      paths:
      - backend:
          serviceName: rs-front
          servicePort: http
        path: /
      - backend:
          serviceName: rs-kibana
          servicePort: http
        path: /kibana

config:
  fullnameOverride: rs-config

registry:
  fullnameOverride: rs-registry
  entrypointOverride:
    waitForIts:
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0

admin-instance:
  fullnameOverride: rs-admin-instance
  entrypointOverride:
   waitForIts:
     - host: {{ group_config_mservices.amqp.host }}
       port: {{ group_config_mservices.amqp.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_config_mservices.postgres.instance.host }}
       port: {{ group_config_mservices.postgres.instance.port }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.config.host }}
       port: {{ group_docker_mservices.config.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.registry.host }}
       port: {{ group_docker_mservices.registry.http }}
       strict: false
       quiet: false
       timeout: 0

admin:
  fullnameOverride: rs-admin
  entrypointOverride:
   waitForIts:
     - host: {{ group_config_mservices.amqp.host }}
       port: {{ group_config_mservices.amqp.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_config_mservices.postgres.init_project.host }}
       port: {{ group_config_mservices.postgres.init_project.port }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.config.host }}
       port: {{ group_docker_mservices.config.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.registry.host }}
       port: {{ group_docker_mservices.registry.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.admin_instance.host }}
       port: {{ group_docker_mservices.admin_instance.http }}
       strict: false
       quiet: false
       timeout: 0

access-instance:
  fullnameOverride: rs-access-instance
  entrypointOverride:
   waitForIts:
     - host: {{ group_config_mservices.amqp.host }}
       port: {{ group_config_mservices.amqp.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_config_mservices.postgres.instance.host }}
       port: {{ group_config_mservices.postgres.instance.port }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.config.host }}
       port: {{ group_docker_mservices.config.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.registry.host }}
       port: {{ group_docker_mservices.registry.http }}
       strict: false
       quiet: false
       timeout: 0

access-project:
  fullnameOverride: rs-access-project
  entrypointOverride:
   waitForIts:
     - host: {{ group_config_mservices.amqp.host }}
       port: {{ group_config_mservices.amqp.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_config_mservices.postgres.init_project.host }}
       port: {{ group_config_mservices.postgres.init_project.port }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.config.host }}
       port: {{ group_docker_mservices.config.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.registry.host }}
       port: {{ group_docker_mservices.registry.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.admin.host }}
       port: {{ group_docker_mservices.admin.http }}
       strict: false
       quiet: false
       timeout: 0

gateway:
  fullnameOverride: rs-gateway
  entrypointOverride:
   waitForIts:
     - host: {{ group_config_mservices.amqp.host }}
       port: {{ group_config_mservices.amqp.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_config_mservices.postgres.init_project.host }}
       port: {{ group_config_mservices.postgres.init_project.port }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.config.host }}
       port: {{ group_docker_mservices.config.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.registry.host }}
       port: {{ group_docker_mservices.registry.http }}
       strict: false
       quiet: false
       timeout: 0
     - host: {{ group_docker_mservices.admin.host }}
       port: {{ group_docker_mservices.admin.http }}
       strict: false
       quiet: false
       timeout: 0

authentication:
  fullnameOverride: rs-authentication
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0


ingest:
  fullnameOverride: rs-ingest
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0

dam:
  fullnameOverride: rs-dam
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0


notifier:
  fullnameOverride: rs-notifier
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.dam.host }}
        port: {{ group_docker_mservices.dam.http }}
        strict: false
        quiet: false
        timeout: 0

fem:
  fullnameOverride: rs-fem
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.dam.host }}
        port: {{ group_docker_mservices.dam.http }}
        strict: false
        quiet: false
        timeout: 0

catalog:
  fullnameOverride: rs-catalog
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.dam.host }}
        port: {{ group_docker_mservices.dam.http }}
        strict: false
        quiet: false
        timeout: 0

order:
  fullnameOverride: rs-order
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.dam.host }}
        port: {{ group_docker_mservices.dam.http }}
        strict: false
        quiet: false
        timeout: 0

processing:
  fullnameOverride: rs-processing
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.dam.host }}
        port: {{ group_docker_mservices.dam.http }}
        strict: false
        quiet: false
        timeout: 0

dataprovider:
  fullnameOverride: rs-dataprovider
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0

storage:
  fullnameOverride: rs-storage
  entrypointOverride:
    waitForIts:
      - host: {{ group_config_mservices.amqp.host }}
        port: {{ group_config_mservices.amqp.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_config_mservices.postgres.init_project.host }}
        port: {{ group_config_mservices.postgres.init_project.port }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.config.host }}
        port: {{ group_docker_mservices.config.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.registry.host }}
        port: {{ group_docker_mservices.registry.http }}
        strict: false
        quiet: false
        timeout: 0
      - host: {{ group_docker_mservices.admin.host }}
        port: {{ group_docker_mservices.admin.http }}
        strict: false
        quiet: false
        timeout: 0
