---
- name: Create HA Proxy config folder
  ansible.builtin.file:
    path: "{{ role_regards_haproxy_config_conf_local }}"
    state: directory
    mode: '0770'
    owner: "{{ role_regards_haproxy_config_container_root_user }}"
    group: "{{ role_regards_haproxy_config_container_root_group }}"
    setype: "{{ role_regards_haproxy_config_setype }}"
    seuser: "{{ role_regards_haproxy_config_seuser }}"

- name: Copy HA Proxy config file
  ansible.builtin.template:
    src: haproxy.cfg
    dest: "{{ role_regards_haproxy_config_conf_local }}"
    mode: '0770'
    owner: "{{ role_regards_haproxy_config_container_root_user }}"
    group: "{{ role_regards_haproxy_config_container_root_group }}"
