apiVersion: v2
name: rs-dam
description: A Helm chart for rs-dam
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: {{ regards_version }}

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: {{ regards_version }}

dependencies:
- name: regards-common
  version: 0.1.0
  repository: "file://../regards-common"
