---
role_regards_workers_secrets_configs_container_root_user: "{{ group_container_root_user }}"
role_regards_workers_secrets_configs_container_root_group: "{{ group_container_root_group }}"
role_regards_workers_secrets_configs_setype: "{{ group_setype }}"
role_regards_workers_secrets_configs_seuser: "{{ group_seuser }}"

role_regards_workers_secrets_configs_container_run_user: "{{ group_container_run_user }}"
role_regards_workers_secrets_configs_container_run_group: "{{ group_container_run_group }}"

# Inventory configs and secrets
role_regards_workers_secrets_configs_configs: "{{ group_docker_workers_configs | default([]) }}"
role_regards_workers_secrets_configs_secrets: "{{ group_docker_workers_secrets | default([]) }}"

role_regards_workers_secrets_configs_inventory_path_configs: "{{ inventory_dir }}/group_vars/regards_nodes/workers/configs"
role_regards_workers_secrets_configs_inventory_path_secrets: "{{ inventory_dir }}/group_vars/regards_nodes/workers/secrets"

role_regards_workers_secrets_configs_configs_destination: "{{ group_workdir_local }}{{ group_stack_name }}/config/regards/workers/configs"
role_regards_workers_secrets_configs_secrets_destination: "{{ group_workdir_local }}{{ group_stack_name }}/config/regards/workers/secrets"
