---
role_regards_init_master_docker_network_name: "{{ group_docker_network_name }}"
role_regards_init_master_docker_network_subnet: "{{ group_docker_network_ip_network }}0/24"
role_regards_init_master_docker_network_gateway: "{{ group_docker_network_ip_network }}1"

role_regards_init_master_workdir_local: "{{ group_workdir_local }}"
role_regards_init_master_config: "{{ group_workdir_local }}{{ group_stack_name }}/config/"
role_regards_init_master_stack: "{{ group_workdir_local }}{{ group_stack_name }}/stack/"
role_regards_init_master_cli: "{{ group_workdir_local }}{{ group_stack_name }}/cli/"

role_regards_init_master_cli_system_install: "/opt/regards/{{ group_stack_name }}/cli/"

role_regards_init_master_workdir_network: "{{ group_workdir_network }}"

role_regards_init_master_container_root_user: "{{ group_container_root_user }}"
role_regards_init_master_container_root_group: "{{ group_container_root_group }}"

role_regards_init_master_container_run_user: "{{ group_container_run_user }}"
role_regards_init_master_container_run_group: "{{ group_container_run_group }}"
role_regards_init_master_setype: "{{ group_setype }}"
role_regards_init_master_seuser: "{{ group_seuser }}"


# CLI files
role_regards_init_master_registry: "{{ group_docker_registry }}"
role_regards_init_master_stack_name: "{{ group_stack_name }}"

role_regards_init_master_mservices: "{{ group_docker_mservices }}"
role_regards_init_master_cots: "{{ group_docker_cots }}"

role_regards_init_public_url: "{{ group_docker_mservices.front.protocol }}://{{ group_docker_mservices.front.host }}:{{ group_docker_mservices.front.port }}"

#Workers
role_regards_init_workers: "{{ group_docker_workers | default([]) }}"
