---
role_regards_init_master_docker_network_name: "{{ group_docker_network_name }}"
role_regards_init_master_validate_certs: "{{ group_validate_certs | default(lookup('ansible.builtin.env', 'DOCKER_TLS_VERIFY')|default(false, true)) }}"
role_regards_init_master_docker_network_subnet: "{{ group_docker_network_ip_network }}0/24"
role_regards_init_master_docker_network_gateway: "{{ group_docker_network_ip_network }}1"

role_regards_init_master_workdir_local: "{{ group_workdir_local }}"
role_regards_init_master_config: "{{ group_workdir_local }}{{ group_stack_name }}/config/"
role_regards_init_master_stack: "{{ group_workdir_local }}{{ group_stack_name }}/stack/"
role_regards_init_master_cli: "{{ group_workdir_local }}{{ group_stack_name }}/cli/"

role_regards_init_master_container_root_user: "{{ group_container_root_user }}"
role_regards_init_master_container_root_group: "{{ group_container_root_group }}"

role_regards_init_master_container_run_user: "{{ group_container_run_user }}"
role_regards_init_master_container_run_group: "{{ group_container_run_group }}"
role_regards_init_master_setype: "{{ group_setype }}"
role_regards_init_master_seuser: "{{ group_seuser }}"


# CLI files
role_regards_init_master_registry: "{{ group_docker_registry }}"
role_regards_init_master_stack_name: "{{ group_stack_name }}"

role_regards_init_master_mservices: "{{ group_docker_mservices | default({}) }}"
role_regards_init_master_mservices_active: "{{ role_regards_init_master_mservices|length > 0 }}"
role_regards_init_master_cots: "{{ group_docker_cots }}"

role_regards_init_front: "{{ role_regards_init_master_mservices.get('front', {}) }}"
role_regards_init_public_url: "{{ role_regards_init_front.protocol | default('http') }}://{{ role_regards_init_front.host | default('localhost') }}:{{ role_regards_init_front.public_port | default(role_regards_init_front.get('port','8080')) }}"

role_regards_init_master_add_autocomplete_on_root_user: "{{ group_enable_cli_autocomplete }}"

# Workers
role_regards_init_workers: "{{ group_docker_workers | default([]) }}"

role_regards_init_config_mservices: "{{ group_config_mservices | default({}) }}"
role_regards_init_ca_certificates: "{{ role_regards_init_config_mservices.get('ca_certificates', []) }}"

role_regards_init_top_level_configs: "{{  (group_docker_mounts | default({})).get('configs', []) }}"
role_regards_init_top_level_secrets: "{{  (group_docker_mounts | default({})).get('secrets', []) }}"
role_regards_init_top_level_volumes: "{{ (group_docker_mounts | default({})).get('volumes', []) }}"
role_regards_init_top_level_regards: "{{  (group_docker_mounts | default({})).get('regards', {}) }}"

role_regards_init_volume_mservices_logs:
  - config
  - registry
  - gateway
  - admin-instance
  - admin
  - authentication
  - dam
  - notifier
  - fem
  - catalog
  - access-instance
  - access-project
  - storage
  - order
  - processing
  - ingest
  - dataprovider
  - worker-manager
  - lta-manager
  - delivery
  - file-catalog
  - file-access
  - file-packager
  - front

role_regards_init_master_rabbitmq_ssl_active: "{{ group_docker_cots_configuration.get('rabbitmq', {}).ssl is defined }}"
role_regards_init_master_rabbitmq_global_active: "{{ role_regards_init_master_cots.get('rabbitmq', {}).global_service is defined }}"
role_regards_init_master_rabbitmq_folder_certificates: "{{ group_workdir_local }}{{ group_stack_name }}/config/rabbitmq/ca-certificates/"
role_regards_init_master_rabbitmq_ssl_certificates_conf: "{{ group_docker_cots_configuration.get('rabbitmq', {}).get('ssl', {}) }}"

role_regards_init_master_grafana_active_default_dashboard: "{{ role_regards_init_master_cots.get('grafana', {}).get('configuration', {}).get('use_generic_dashboards', True) }}"

# MinIO
role_regards_init_master_minio_ssl_active: "{{ group_docker_cots.get('minio', {}).ssl is defined }}"
role_regards_init_master_minio_ssl_ca_active: "{{ group_docker_cots.get('minio', {}).get('ssl', {}).ca is defined }}"
role_regards_init_master_minio_internal_ssl_active: "{{ group_docker_cots.get('minio', {}).ssl_internal is defined }}"
role_regards_init_master_minio_ssl_internal_certificates_conf: "{{ group_docker_cots.get('minio', {}).get('ssl_internal', {}) }}"
role_regards_init_master_minio_ssl_certificates_conf: "{{ group_docker_cots.get('minio', {}).get('ssl', {}) }}"

# MinIO mc
role_regards_init_master_minio_mc_log_ca_active: "{{ group_docker_cots.get('minio_mc_log', {}).ca is defined }}"
role_regards_init_master_minio_mc_log_ca: "{{ group_docker_cots.get('minio_mc_log', {}).get('ca') }}"
