---
role_regards_elasticsearch_config_conf_local: "{{ group_workdir_local }}{{ group_stack_name }}/config/elasticsearch/"

role_regards_elasticsearch_config_container_root_user: "{{ group_container_root_user }}"
role_regards_elasticsearch_config_container_root_group: "{{ group_container_root_group }}"

role_regards_elasticsearch_config_setype: "{{ group_setype }}"
role_regards_elasticsearch_config_seuser: "{{ group_seuser }}"


role_regards_elasticsearch_config_elasticsearch_defined: "{{ group_docker_cots.elasticsearch is defined }}"
role_regards_elasticsearch_config_elasticsearch_logs_defined: "{{ group_docker_cots.elasticsearch_logs is defined }}"

role_regards_elasticsearch_config_elasticsearch: "{{ group_docker_cots.elasticsearch | default({})}}"
role_regards_elasticsearch_config_elasticsearch_logs: "{{ group_docker_cots.elasticsearch_logs | default({})}}"
