name_space_uid: 1400000
name_space_gid: 1400000
name_space_range: 100000
docker_group_gid: 1400117

certificates_email: regards@cnes.fr

swarm_manager_eth: "ansible_{{ global_stack.docker.network_interface }}"

docker_bip: 10.122.20.1/24
docker_ingress_network: 10.122.22.0/24
docker_ingress_network_gateway: 10.122.22.1
docker_gwbridge_network: 10.122.21.0/24
#docker_dns:
#  - 8.8.8.8

docker_data_root: "{{ global_stack.docker.workdir }}"
docker_storage_driver: overlay2

docker_http_proxy: "{{ global_proxy.url | default(None) }}"
docker_no_proxy:  "{{ global_proxy.no_proxy | default(None) }}"

environment_http_proxy: "{{ global_proxy.url | default(None) }}"
environment_https_proxy: "{{ global_proxy.url | default(None) }}"
environment_no_proxy: "{{ global_proxy.no_proxy | default(None) }}"
yum_proxy: "{{ global_proxy.url | default(None) }}"
